Rug-warrior: /root/Desktop/rug-warrior/libs/behavior/1meter.c File Reference
1meter.c File Reference
Functions
void main ()
Function Documentation
void main ()
Run over a distance of 1.20 meters
Last update: -
Version
Final
Definition at line 7 of file 1meter.c.
References _motor_distance_, _motor_initial_speed_, _motor_left_speed_, _motor_right_speed_, encoder_aux(), init_motors(), printn(), running(), and sleep().
 {
     _motor_distance_ = (int)(600./1.178)-1;
     _motor_initial_speed_ = 100;
     printf("Running for\n1.2 meter");
     init_motors();
     start_process(encoder_aux());
     start_process(running());
     while(1)
     {
         printf("Running Test   ");
         printn(_right_enc_counts_-_left_enc_counts_,5);
         printf(" ");
         printn(_motor_right_speed_,5);
         printn(_motor_left_speed_,5);
         printf("\n");
         sleep(0.1);
     }
 }