rug-warrior: /root/Desktop/rug-warrior/libs/music/tunes.c File Reference
tunes.c File Reference
Functions
void pp ()
void wate ()
void classics ()
void charge ()
void looney_tune ()
void benny ()
void musicbox ()
void play (char song[])
void music_command (int c)
void play_reset ()
void play_note (int note, int duration)
void play_note_2 (int note, int duration)
void bicycle ()
Variables
char pp_song [] = "1#d 4e3r1#f4g3r1#d 3e1#f3g1c3bD1e3g1b 8&b2b2a2g2e2d10e 7r1#d 4e3r1#f4g3r1#d 3e1#f3g1c3b1g3b1e 28&e D3r1#d 4e3r1#f4g3r1#d 3e1#f3g1c3bD1e3g1b 8&b2b2a2g2e2d10e 12r U3e1d3b1a3g1#f 1&b3a1&b3a1&b3a1&b3a 2g2e2d2e18e 8r 2g2e2d2e18e 8r 2g2e2d2e18e"
char w_song [] = "1c2f1f2f1g2a1a2a1f2g1g2g1e4f1r 1f2a1a2a1&b2c1c2c1c2d1c2&b1a4g1r 1gU2d1d2d1c2d1e2f1d2c1d2c1&b4a1r D1c2f1f2f1g2a1a2a1f2g1g2f1e5f"
char classics_song [] = "4g2c2d4c4g4a2g2f2e2c2d2e2f2g2a2b10c2r 4c4b4c2d2b2c2d2e2#f4g2#f2e4d2g2#f4g4d4e2d2c2b2g2a2b2c2b2c2d2e2d2e2#f12g"
char charge_song [] = "1c1e1g2c1r1g4c"
char benny_song [] = "1c1d1cU2f2f1d1c1#g1a2c2d1c1a1#g1g2f1f1f1a1c2d5c1c1d1c2f2f1d1c1#g1a2c2d1c1a1#g1g2c1c1c1e1g2e5c1c1d1c2f2f2f2f2f2f1d1c1g1a2#a2#a2#a2#a1d1#a1d1#aU1f3g1a1#g1a1#g1a3c1a1#g1#a5f1a1#f1#d1cU1#g1f1d1b4f"
char mb_song1 [] = "2c2e2g2eU2c2g2e2gD2c2e2g2eU2c2g2e 2c2c2g2c2e2c2e2gD2cU2c2b2a7g1r 2g2g2f2d2b2g2b2d2f2e2cU2a7g1r D2c2c2g2c2e2c2e2gD2cU2c2b2a7g1r 2g2g2f2d2b2g2b2d2b2c2gU2e4c 2c2e2g2c2a2f2c2a2c2f2a2gD2cU2a4g D2g2b2d2g2f2d2b2g2b2d2f2e2cU2a4g D2c2e2g2c2a2f2c2a2c2f2a2gD2cU2a4g D2g2b2d2g2f2d2b2g2b2d2b2c2gU2e7c"
char mb_song2 [] = "2c2e2g2eU2c2g2e2gD2c2e2g2eU2c2g2e 2c2c2g2c2e2c2e2gD2cU2c2b2a7g1r U2g2g2f2d2b2g2b2d2f2e2cU2a7g1r DD2c2c2g2c2e2c2e2gD2cU2c2b2a7g1r U2g2g2f2d2b2g2b2d2b2c2gU2e4c 2c2e2g2c2a2f2c2a2c2f2a2gD2cU2a4g D2g2b2d2g2f2d2b2g2b2d2f2e2cU2a4g DD2c2e2g2c2a2f2c2a2c2f2a2gD2cU2a4g U2g2b2d2g2f2d2b2g2b2d2b2c2gU2e7c"
char looney_tune_song [] = "U3e1d2c2d2e2d2e2c2d2d2d6d2r 3d1c2b2c2d2#c2d2b2c2c2c6c"
int tempo = 12
long time
long newtime
int music_current_command = 'o'
int music_next_command = 0
Function Documentation
void benny ()
Definition at line 43 of file tunes.c.
References benny_song, and play().
 {
     play(benny_song);
 }
void bicycle ()
Definition at line 214 of file tunes.c.
References sleep(), and tone().
 {
     tone(2093.0,0.769);
     tone(1760.0,0.769);
     tone(1396.9,0.769);
     tone(1046.5,0.769);
     tone(1174.7,0.192);
     tone(1318.5,0.192);
     tone(1396.9,0.192);
     tone(1174.7,0.385);
     tone(1396.9,0.192);
     tone(1046.5,0.962);
     sleep(0.385);
     tone(1568.0,0.769);
     tone(2093.0,0.769);
     tone(1760.0,0.769);
     tone(1396.9,0.769);
     tone(1174.7,0.192);
     tone(1318.5,0.192);
     tone(1396.9,0.192);
     tone(1568.0,0.385);
     tone(1760.0,0.192);
     tone(1568.0,0.962);
     sleep(0.385);
     tone(1760.0,0.192);
     tone(1864.7,0.192);
     tone(1760.0,0.192);
     tone(1568.0,0.192);
     tone(2093.0,0.385);
     tone(1760.0,0.192);
     tone(1568.0,0.192);
     tone(1396.9,0.962);
     tone(1568.0,0.192);
     tone(1760.0,0.385);
     tone(1396.9,0.192);
     tone(1174.7,0.385);
     tone(1396.9,0.192);
     tone(1174.7,0.192);
     tone(1046.5,0.962);
     tone(1046.5,0.192);
     tone(1396.9,0.385);
     tone(1760.0,0.192);
     tone(1568.0,0.385);
     tone(1046.5,0.192);
     tone(1396.9,0.385);
     tone(1760.0,0.192);
     tone(1568.0,0.192);
     tone(1760.0,0.192);
     tone(1864.7,0.192);
     tone(2093.0,0.192);
     tone(1760.0,0.192);
     tone(1396.9,0.192);
     tone(1568.0,0.385);
     tone(1046.5,0.192);
     tone(1396.9,0.962);
 }
void charge ()
Definition at line 32 of file tunes.c.
References charge_song, and play().
 {
     play(charge_song);
 }
void classics ()
Definition at line 27 of file tunes.c.
References classics_song, and play().
 {
     play(classics_song);
 }
void looney_tune ()
Definition at line 37 of file tunes.c.
References looney_tune_song, play(), and tempo.
 {
     tempo=8;
     play(looney_tune_song);
     tempo=12;
 }
void music_command (int c)
Definition at line 164 of file tunes.c.
References c, and music_current_command.
Referenced by play(), and play_note_2().
 {
     music_current_command = c;
 }
void musicbox ()
Definition at line 48 of file tunes.c.
References mb_song1, mb_song2, and play().
 {
     play(mb_song1);
     play(mb_song2);
 }
void play (char song[])
Definition at line 61 of file tunes.c.
References beep(), music_command(), music_next_command, note(), play_note(), play_reset(), and sleep().
Referenced by benny(), charge(), classics(), looney_tune(), musicbox(), pp(), and wate().
 {
     int i, duration, accidental, delta, note, rest;
     int notes[]= {0,2,3,5,7,8,10};
     int old_note= 30;
     play_reset();
     i= 0;
     while(song[i])
     {
         while(1)
         {
             while(song[i] == ' ') ++i;
             if(song[i] == 'X')
             {
                 ++i;
                 music_next_command= song[i];
                 ++i;
             }
             else break;
         }
         if(!song[i]) break;
         while(song[i] == 'D')
         {
             old_note -= 12;
             ++i;
         }
         while(song[i] == 'U')
         {
             old_note += 12;
             ++i;
         }
         if('0' <= song[i] && song[i] <= '9')
         {
             duration= 0;
             while('0' <= song[i] && song[i] <= '9')
             {
                 duration = duration * 10 + song[i]-'0';
                 ++i;
             }
         }
         if(song[i] == '#')
         {
             accidental= 1;
             ++i;
         }
         else if(song[i] == '&')
         {
             accidental= -1;
             ++i;
         }
         else
         {
             accidental= 0;
         }
         if(song[i] == 'r') rest= 1;
         else
         {
             if(song[i] < 'a' || song[i] > 'g')
             {
                 printf("\nBad note:%c\n", song[i]);
                 beep();
                 beep();
                 beep();
                 sleep(5.0);
                 return;
             }
             note= notes[song[i]-'a'] + accidental;
             rest= 0;
         }
         i++;
         if(rest)
         {
             play_note(0, duration);
         }
         else
         {
             delta= note - (old_note % 12);
             old_note += delta;
             if(delta > 5) old_note -= 12;
             if(delta < -5) old_note += 12;
             play_note(old_note, duration);
         }
     }
     play_note(0, 1);
     music_command('o');
 }
void play_note (int note, int duration)
Definition at line 176 of file tunes.c.
References play_note_2().
Referenced by play().
 {
     play_note_2(note, duration*7);
     play_note_2(0, duration);
 }
void play_note_2 (int note, int duration)
Definition at line 182 of file tunes.c.
References beeper_off(), beeper_on(), music_command(), music_current_command, music_next_command, newtime, set_beeper_pitch(), and tempo.
Referenced by play_note().
 {
     float freq;
     int   period;
     if(note)
     {
         freq= 55.0 * (2. ^ (((float) note) / 12.));
     }
     while(mseconds() < newtime);
     if(note)
     {
         set_beeper_pitch(freq);
         beeper_on();
     }
     else
     {
         beeper_off();
     }
     if(music_next_command &&
             music_current_command != music_next_command)
     {
         music_command(music_next_command);
         music_next_command= 0;
     }
     newtime += (long)(duration * tempo);
 }
void play_reset ()
Definition at line 170 of file tunes.c.
References newtime, and time.
Referenced by play().
 {
     time = mseconds();
     newtime = time+100L;
 }
void pp ()
Definition at line 17 of file tunes.c.
References play(), and pp_song.
 {
     play(pp_song);
 }
void wate ()
Definition at line 22 of file tunes.c.
References play(), and w_song.
 {
     play(w_song);
 }
Variable Documentation
char benny_song[] = "1c1d1cU2f2f1d1c1#g1a2c2d1c1a1#g1g2f1f1f1a1c2d5c1c1d1c2f2f1d1c1#g1a2c2d1c1a1#g1g2c1c1c1e1g2e5c1c1d1c2f2f2f2f2f2f1d1c1g1a2#a2#a2#a2#a1d1#a1d1#aU1f3g1a1#g1a1#g1a3c1a1#g1#a5f1a1#f1#d1cU1#g1f1d1b4f"
Definition at line 9 of file tunes.c.
Referenced by benny().
char charge_song[] = "1c1e1g2c1r1g4c"
Definition at line 7 of file tunes.c.
Referenced by charge().
char classics_song[] = "4g2c2d4c4g4a2g2f2e2c2d2e2f2g2a2b10c2r 4c4b4c2d2b2c2d2e2#f4g2#f2e4d2g2#f4g4d4e2d2c2b2g2a2b2c2b2c2d2e2d2e2#f12g"
Definition at line 5 of file tunes.c.
Referenced by classics().
char looney_tune_song[] = "U3e1d2c2d2e2d2e2c2d2d2d6d2r 3d1c2b2c2d2#c2d2b2c2c2c6c"
Definition at line 15 of file tunes.c.
Referenced by looney_tune().
char mb_song1[] = "2c2e2g2eU2c2g2e2gD2c2e2g2eU2c2g2e 2c2c2g2c2e2c2e2gD2cU2c2b2a7g1r 2g2g2f2d2b2g2b2d2f2e2cU2a7g1r D2c2c2g2c2e2c2e2gD2cU2c2b2a7g1r 2g2g2f2d2b2g2b2d2b2c2gU2e4c 2c2e2g2c2a2f2c2a2c2f2a2gD2cU2a4g D2g2b2d2g2f2d2b2g2b2d2f2e2cU2a4g D2c2e2g2c2a2f2c2a2c2f2a2gD2cU2a4g D2g2b2d2g2f2d2b2g2b2d2b2c2gU2e7c"
Definition at line 11 of file tunes.c.
Referenced by musicbox().
char mb_song2[] = "2c2e2g2eU2c2g2e2gD2c2e2g2eU2c2g2e 2c2c2g2c2e2c2e2gD2cU2c2b2a7g1r U2g2g2f2d2b2g2b2d2f2e2cU2a7g1r DD2c2c2g2c2e2c2e2gD2cU2c2b2a7g1r U2g2g2f2d2b2g2b2d2b2c2gU2e4c 2c2e2g2c2a2f2c2a2c2f2a2gD2cU2a4g D2g2b2d2g2f2d2b2g2b2d2f2e2cU2a4g DD2c2e2g2c2a2f2c2a2c2f2a2gD2cU2a4g U2g2b2d2g2f2d2b2g2b2d2b2c2gU2e7c"
Definition at line 13 of file tunes.c.
Referenced by musicbox().
int music_current_command = 'o'
Definition at line 57 of file tunes.c.
Referenced by music_command(), and play_note_2().
int music_next_command = 0
Definition at line 59 of file tunes.c.
Referenced by play(), and play_note_2().
long newtime
Definition at line 55 of file tunes.c.
Referenced by play_note_2(), and play_reset().
char pp_song[] = "1#d 4e3r1#f4g3r1#d 3e1#f3g1c3bD1e3g1b 8&b2b2a2g2e2d10e 7r1#d 4e3r1#f4g3r1#d 3e1#f3g1c3b1g3b1e 28&e D3r1#d 4e3r1#f4g3r1#d 3e1#f3g1c3bD1e3g1b 8&b2b2a2g2e2d10e 12r U3e1d3b1a3g1#f 1&b3a1&b3a1&b3a1&b3a 2g2e2d2e18e 8r 2g2e2d2e18e 8r 2g2e2d2e18e"
Definition at line 1 of file tunes.c.
Referenced by pp().
int tempo = 12
Definition at line 54 of file tunes.c.
Referenced by looney_tune(), and play_note_2().
long time
Definition at line 55 of file tunes.c.
Referenced by play_reset().
char w_song[] = "1c2f1f2f1g2a1a2a1f2g1g2g1e4f1r 1f2a1a2a1&b2c1c2c1c2d1c2&b1a4g1r 1gU2d1d2d1c2d1e2f1d2c1d2c1&b4a1r D1c2f1f2f1g2a1a2a1f2g1g2f1e5f"
Definition at line 3 of file tunes.c.
Referenced by wate().