rug-warrior: /root/Desktop/rug-warrior/libs/base/lib_ic.c File Reference
lib_ic.c File Reference
Functions
void reset_system_time ()
float seconds ()
void sleep (float seconds)
void msleep (long msec)
void beep ()
void tone (float frequency, float length)
void beeper_on ()
void beeper_off ()
void set_beeper_pitch (float frequency)
long timer_create_mseconds (long timeout)
long timer_create_seconds (float timeout)
int timer_done (long timer)
int analog (int port)
void hog_processor ()
Variables
persistent int test_number
Function Documentation
int analog (int port)
Definition at line 111 of file lib_ic.c.
Referenced by bumper(), main(), and sample_sound().
 {
     poke(0x1039, 0b10000000);
     poke(0x1030, port);
     return peek(0x1031);
 }
void beep ()
Old freq was 500, but 1000 sounds louder
Definition at line 57 of file lib_ic.c.
References tone().
Referenced by play().
 {
     tone(1000., .3);
 }
void beeper_off ()
Definition at line 83 of file lib_ic.c.
Referenced by play_note_2(), and warb().
 {
     bit_clear(0x1022, 0b00001000);
     bit_clear(0x1020, 0b00000001);
     pokeword(0x26, 0);
     bit_clear(0x1000, 0b00001000);  /* turn power to spkr off */
 }
void beeper_on ()
Definition at line 77 of file lib_ic.c.
Referenced by play_note_2(), and warb().
 {
     bit_set(0x1020, 0b00000001);
     bit_set(0x1022, 0b00001000);
 }
void hog_processor ()
gives process that calls it 256 ticks (over 1/4 sec) more to run before being swapped out call repeatedly to hog processor indefinitely
Definition at line 127 of file lib_ic.c.
 {
     poke(0x0a, 0);
 }
void msleep (long msec)
Definition at line 40 of file lib_ic.c.
Referenced by ir_detect(), and sleep().
 {
     long end_time= mseconds() + msec;
     while(1)
     {
         /* if the following test doesn't execute at least once a second,
            msleep may not halt */
         long done= mseconds()-end_time;
         if(done >= 0L && done <= 1000L) break;
     }
 }
void reset_system_time ()
Definition at line 21 of file lib_ic.c.
 {
     pokeword(0x14, 0);
     pokeword(0x12, 0);
 }
float seconds ()
returns valid time from 0 to 32,767 minutes (approx)
Definition at line 30 of file lib_ic.c.
 {
     return ((float) mseconds()) / 1000.;
 }
void set_beeper_pitch (float frequency)
Definition at line 91 of file lib_ic.c.
Referenced by play_note_2(), and warb().
 {
     pokeword(0x26, (int)(1E6 / frequency));
 }
void sleep (float seconds)
Definition at line 35 of file lib_ic.c.
References msleep().
Referenced by bicycle(), capture_command(), echo_control(), main(), ping(), play(), rotate(), rpt(), scan(), tone(), twitch_aux(), and warb().
 {
     msleep((long)(seconds * 1000.));
 }
long timer_create_mseconds (long timeout)
Definition at line 96 of file lib_ic.c.
 {
     return mseconds() + timeout;
 }
long timer_create_seconds (float timeout)
Definition at line 101 of file lib_ic.c.
 {
     return mseconds() + (long)(timeout * 1000.);
 }
int timer_done (long timer)
Definition at line 106 of file lib_ic.c.
 {
     return timer < mseconds();
 }
void tone (float frequency, float length)
1/2 cycle delay in .5us goes in 0x26 and 0x27
Definition at line 65 of file lib_ic.c.
References sleep().
Referenced by beep(), bicycle(), and note().
 {
     pokeword(0x26, (int)(1E6 / frequency));
     bit_set(0x1020, 0b00000001);
     sleep(length);
     bit_clear(0x1020, 0b00000001);
     /*  following is important to reduce # of interrupts
     when tone is off  */
     pokeword(0x26, 0);
     bit_clear(0x1000, 8);
 }
Variable Documentation
persistent int test_number
Definition at line 10 of file lib_ic.c.