rug-warrior: /root/Desktop/rug-warrior/libs/test/encoder.c File Reference
encoder.c File Reference
Functions
void encoder_aux ()
void main ()
Variables
int _l_enc_counts = 0
int _r_enc_counts = 0
Function Documentation
void encoder_aux ()
Definition at line 5 of file encoder.c.
References _l_enc_counts, _r_enc_counts, left_shaft(), and right_shaft().
 {
    /* Trigger on Hi -> Low transition */
     int l_old, r_old, l_new, r_new;
     while(1)
     {
         l_new = left_shaft();
         r_new = right_shaft();
         /* (old and not new) => 1 -> 0 transition */
         if(l_old & ~l_new)
             _l_enc_counts++;
         if(r_old & ~r_new)
             _r_enc_counts++;
         /* Update transition detector */
         l_old = l_new;
         r_old = r_new;
     }
 }
void main ()
Definition at line 28 of file encoder.c.
References _l_enc_counts, _r_enc_counts, encoder_aux(), left_shaft(), printn(), right_shaft(), and sleep().
 {
     start_process(encoder_aux());            /* Show SE state on LEDs */
     while(1)
     {
         printf("Encoders Test   ");
         printf("L");
         if(left_shaft()) printf("*");        /* Left SE is ON */
         else             printf("%c",0xA5);  /* Left SE is OFF */
         printn(_l_enc_counts,5);             /* Report Left clicks */
         printf(" R");
         if(right_shaft()) printf("*");       /* Right SE is ON */
         else              printf("%c",0xA5); /* Right SE is OFF */
         printn(_r_enc_counts,5);             /* Report Right clicks */
         printf("\n");
         sleep(0.3);
     }
 }
Variable Documentation
int _l_enc_counts = 0
Definition at line 1 of file encoder.c.
Referenced by encoder_aux(), and main().
int _r_enc_counts = 0
Definition at line 2 of file encoder.c.
Referenced by encoder_aux(), and main().