rug-warrior: /root/Desktop/rug-warrior/libs/test/sonar.c File Reference
sonar.c File Reference
Functions
void main ()
Function Documentation
void main ()
Definition at line 1 of file sonar.c.
References init_sonar(), ping(), range(), set_servo(), sleep(), sonar_init_servo(), and sonar_servo_off().
 {
     int pos;
     pos = -100;
     init_sonar();
     sonar_init_servo();
     while(pos <= 100)
     {
         printf("%d - ", pos);
         set_servo(pos);
         ping();
         printf("%f\n", range());
         pos += 10;
         sleep(1.);
     }
     sonar_servo_off();
 }