rug-warrior: /root/Desktop/rug-warrior/libs/shared/motor.c File Reference
motor.c File Reference
Macros
#define R_MOTOR 1
#define L_MOTOR 2
Functions
void running ()
void encoder_aux ()
void encoder_reset ()
float feetToMotor (float feet, int speed)
void rotate (int flags, float angle, int speed)
Variables
int _left_enc_counts_ = 0
int _right_enc_counts_ = 0
int _motor_right_speed_ = 0
int _motor_left_speed_ = 0
int _motor_distance_ = 0
Macro Definition Documentation
#define L_MOTOR 2
Definition at line 2 of file motor.c.
#define R_MOTOR 1
Definition at line 1 of file motor.c.
Referenced by main().
Function Documentation
void encoder_aux ()
count the switching state of encoders value are stored into left_enc_counts and right_enc_counts use this function under parallele thread
Definition at line 48 of file motor.c.
References _left_enc_counts_, _right_enc_counts_, left_shaft(), and right_shaft().
Referenced by main().
 {
     int l_old, r_old, l_new, r_new;
     while(1)
     {
         l_new = left_shaft();
         r_new = right_shaft();
         if(l_old & ~l_new)
             _left_enc_counts_++;
         if(r_old & ~r_new)
             _right_enc_counts_++;
         l_old = l_new;
         r_old = r_new;
     }
 }
void encoder_reset ()
check if encoder_aux() process are not in running state can be not thread-safe
Definition at line 73 of file motor.c.
References _left_enc_counts_, and _right_enc_counts_.
 {
     _left_enc_counts_ = 0;
     _right_enc_counts_ = 0;
 }
float feetToMotor (float feet, int speed)
calculate the time needed to run in x feet with given speed [-100 : 100]
Definition at line 83 of file motor.c.
Referenced by rotate().
 {
     float tmp = (float)speed;
     float inv = 100./tmp;
     return (feet/0.67)*inv;
 }
void rotate (int flags, float angle, int speed)
flags : R_MOTOR, L_MOTOR, R_MOTOR | L_MOTOR angle : degree speed : [-100 : 0] U [0 : 100]
Definition at line 95 of file motor.c.
References cmToFeet(), feetToMotor(), motor(), PI, sleep(), and stop().
Referenced by main().
 {
     int invert;
     float radius = 14.;
     if(flags < 0 || flags > 3)
         return;
     invert = 1;
     if(flags == 3)
     {
         angle /= 2.;
         invert = -1;
         radius /= 2.;
     }
     motor(0, speed*(flags & 1));
     motor(1, speed*(flags & 2)*invert);
     /* calculate the time for the angle */
     sleep(feetToMotor(cmToFeet((angle/360.)*2.*PI*radius), speed));
     stop();
 }
void running ()
start it with thread dependency : encoder_aux() process
Definition at line 14 of file motor.c.
References _left_enc_counts_, _motor_distance_, _motor_left_speed_, _motor_right_speed_, _right_enc_counts_, and motor().
Referenced by main().
 {
     int diff;
     while(1)
     {
         diff = _left_enc_counts_ - _right_enc_counts_;
         if(diff < -1)
         {
             _motor_right_speed_ += 1;
             _motor_left_speed_ -= 1;
         }
         if(diff > 1)
         {
             _motor_right_speed_ -= 1;
             _motor_left_speed_ += 1;
         }
         if(_left_enc_counts_ >= _motor_distance_) _motor_left_speed_ = 0;
         if(_right_enc_counts_ >= _motor_distance_) _motor_right_speed_ = 0;
         motor(0, _motor_left_speed_);
         motor(1, _motor_right_speed_);
     }
 }
Variable Documentation
int _left_enc_counts_ = 0
Definition at line 4 of file motor.c.
Referenced by encoder_aux(), encoder_reset(), main(), and running().
int _motor_distance_ = 0
Definition at line 8 of file motor.c.
Referenced by main(), and running().
int _motor_left_speed_ = 0
Definition at line 7 of file motor.c.
Referenced by main(), and running().
int _motor_right_speed_ = 0
Definition at line 6 of file motor.c.
Referenced by main(), and running().
int _right_enc_counts_ = 0
Definition at line 5 of file motor.c.
Referenced by encoder_aux(), encoder_reset(), main(), and running().