rug-warrior: /root/Desktop/rug-warrior/libs/behavior/1meter.c File Reference
1meter.c File Reference
Functions
void main ()
Function Documentation
void main ()
Definition at line 13 of file 1meter.c.
References _left_enc_counts_, _motor_distance_, _motor_left_speed_, _motor_right_speed_, _right_enc_counts_, encoder_aux(), init_motors(), printn(), running(), and sleep().
 {
     _motor_distance_ = 100;
     _motor_right_speed_ = 100;
     _motor_left_speed_ = 100;
     printf("runing for\n1.2 meter");
     init_motors();
     start_process(encoder_aux());
     start_process(running());
     while(1)
     {
         printf("running Test   ");
         printn(_right_enc_counts_-_left_enc_counts_,5);
         printf("\n");
         sleep(0.1);
     }
 }