Rug-warrior: /mnt/midnight/rug-warrior/libs/base/lib_ic.c File Reference
lib_ic.c File Reference
Functions
void reset_system_time ()
float seconds ()
void sleep (float seconds)
void msleep (long msec)
void beep ()
void tone (float frequency, float length)
void beeper_on ()
void beeper_off ()
void set_beeper_pitch (float frequency)
long timer_create_mseconds (long timeout)
long timer_create_seconds (float timeout)
int timer_done (long timer)
int analog (int port)
void hog_processor ()
Variables
persistent int test_number
Function Documentation
int analog (int port)
return the value of sensor port numbered range in [0 - 255]
Definition at line 129 of file lib_ic.c.
Referenced by bumper(), digital(), display_info(), go_light_stop(), light_diff(), light_environnement(), main(), and sample_sound().
 {
     poke(0x1039, 0b10000000);
     poke(0x1030, port);
     return peek(0x1031);
 }
void beep ()
Old freq was 500 for a periode of 0.3second
Definition at line 52 of file lib_ic.c.
References tone().
Referenced by analog(), digital(), play(), start_press(), and stop_press().
 {
     tone(1000., .3);
 }
void beeper_off ()
disable beeper output
Definition at line 84 of file lib_ic.c.
Referenced by init_sonar(), play_note_2(), tone(), and warb().
 {
     bit_clear(0x1022, 0b00001000);
     bit_clear(0x1020, 0b00000001);
     pokeword(0x26, 0);
     bit_clear(0x1000, 0b00001000);  /* turn power to spkr off */
 }
void beeper_on ()
enable beeper output
Definition at line 75 of file lib_ic.c.
Referenced by play_note_2(), tone(), and warb().
 {
     bit_set(0x1020, 0b00000001);
     bit_set(0x1022, 0b00001000);
 }
void hog_processor ()
gives process that calls it 256 ticks (over 1/4 sec) more to run before being swapped out call repeatedly to hog processor indefinitely
Definition at line 145 of file lib_ic.c.
 {
     poke(0x0a, 0);
 }
void msleep (long msec)
yield the current process for
Definition at line 35 of file lib_ic.c.
Referenced by ir_detect(), and sleep().
 {
     long end_time= mseconds() + msec;
     while(1)
     {
         /* if the following test doesn't execute at least once a second,
            msleep may not halt */
         long done= mseconds()-end_time;
         if(done >= 0L && done <= 1000L) break;
     }
 }
void reset_system_time ()
restart the systeme timer seconds() return 0 after this call
Definition at line 10 of file lib_ic.c.
 {
     pokeword(0x14, 0);
     pokeword(0x12, 0);
 }
float seconds ()
returns valid time from 0 to 32,767 minutes (approx)
Definition at line 19 of file lib_ic.c.
 {
     return ((float) mseconds()) / 1000.;
 }
void set_beeper_pitch (float frequency)
set the bepper tone to be frequency Hz the subsequent function is then used to turn the bepper on
Definition at line 96 of file lib_ic.c.
Referenced by play_note_2(), tone(), and warb().
 {
     pokeword(0x26, (int)(1E6 / frequency));
 }
void sleep (float seconds)
yield the current process for
Definition at line 27 of file lib_ic.c.
References msleep().
Referenced by bicycle(), capture_command(), check_encoder(), detect_distance_sonar(), echo_control(), escape(), frob(), main(), maze_process(), move_behind(), ping(), play(), reset_encoder_aux(), rotate_test_all_for(), rpt(), running(), running_forever(), scan(), scan_display_position(), tone(), twitch_aux(), and warb().
 {
     msleep((long)(seconds * 1000.));
 }
long timer_create_mseconds (long timeout)
return the current time (ms) increased by (ms)
Definition at line 104 of file lib_ic.c.
Referenced by maze_process().
 {
     return mseconds() + timeout;
 }
long timer_create_seconds (float timeout)
return the current time (sec) increased by (ms)
Definition at line 112 of file lib_ic.c.
 {
     return mseconds() + (long)(timeout * 1000.);
 }
int timer_done (long timer)
check if the given (previous timer) are outdated
Definition at line 120 of file lib_ic.c.
Referenced by maze_process().
 {
     return timer < mseconds();
 }
void tone (float frequency, float length)
1/2 cycle delay in .5us goes in 0x26 and 0x27
Definition at line 60 of file lib_ic.c.
References sleep().
Referenced by beep(), bicycle(), and note().
 {
     pokeword(0x26, (int)(1E6 / frequency));
     bit_set(0x1020, 0b00000001);
     sleep(length);
     bit_clear(0x1020, 0b00000001);
     /*  following is important to reduce # of interrupts
     when tone is off  */
     pokeword(0x26, 0);
     bit_clear(0x1000, 8);
 }
Variable Documentation
persistent int test_number
reset button states
Definition at line 4 of file lib_ic.c.
Referenced by main().