Rug-warrior: /root/Desktop/rug-warrior/libs/music/cof.c File Reference
cof.c File Reference
Functions
void note (float freq, float dur)
void cof ()
Variables
float octave = 440.0
float a0 = octave * 1.000
float b0 = (octave * 1.143)
float c = (octave * 1.218)
float d = (octave * 1.375)
float e = (octave * 1.542)
float f = (octave * 1.628)
float g = (octave * 1.810)
float a = (octave * 2.000)
float b = (octave * 2.0 * 1.143)
float c2 = (octave * 2.0 * 1.218)
float q = 0.25
float h = (2.0 * q)
float dh = (3.0 * q)
int note_display = 0
Function Documentation
void cof ()
Play a basic music "piezo" for test issue
Definition at line 97 of file cof.c.
References a, b, c, c2, dh, e, f, g, h, note(), and q.
Referenced by main().
 {
     note(c,q);
     note(f,q);
     note(g,q);
     note(a,q);
     note(g,dh);
     note(e,5.0 * q);
     note(c,q);
     note(f,q);
     note(g,q);
     note(a,q);
     note(g,8.0 * q);
     note(c,q);
     note(f,q);
     note(g,q);
     note(a,q);
     note(g,dh);
     note(e,5.0 * q);
     note(g,q);
     note(f,q);
     note(e,q);
     note(c,q);
     note(c,5.0 * q);
     note(c2,q);
     note(b,q);
     note(a,q);
     note(g,q);
     note(b,h);
     note(g,q);
     note(a,h);
     note(f,q);
     note(g,h);
     note(c2,q);
     note(b,q);
     note(a,q);
     note(g,q);
     note(b,8.0 * q);
     note(c2,q);
     note(b,q);
     note(a,q);
     note(g,q);
     note(b,h);
     note(g,q);
     note(a,h);
     note(f,q);
     note(g,h);
     note(g,q);
     note(f,q);
     note(e,q);
     note(c,q);
     note(c,7.0 * q);
 }
void note (float freq, float dur)
Play a note with given frequency & time can print as display with note_display > 0
Definition at line 86 of file cof.c.
References note_display, and tone().
Referenced by cof(), main(), and play().
 {
     if(note_display)
         printf("Piezo Test      freq%f\n", freq);
     tone(freq,dur);
 }
Variable Documentation
float a = (octave * 2.000)
tonne for piezo test
Definition at line 50 of file cof.c.
Referenced by cof(), and min().
float a0 = octave * 1.000
tonne for piezo test
Definition at line 15 of file cof.c.
float b = (octave * 2.0 * 1.143)
tonne for piezo test
Definition at line 55 of file cof.c.
Referenced by cof(), and min().
float b0 = (octave * 1.143)
tonne for piezo test
Definition at line 20 of file cof.c.
float c = (octave * 1.218)
tonne for piezo test
Definition at line 25 of file cof.c.
Referenced by cof(), and music_command().
float c2 = (octave * 2.0 * 1.218)
tonne for piezo test
Definition at line 60 of file cof.c.
Referenced by cof().
float d = (octave * 1.375)
tonne for piezo test
Definition at line 30 of file cof.c.
float dh = (3.0 * q)
Dotted half
Definition at line 75 of file cof.c.
Referenced by cof().
float e = (octave * 1.542)
tonne for piezo test
Definition at line 35 of file cof.c.
Referenced by cof().
float f = (octave * 1.628)
tonne for piezo test
Definition at line 40 of file cof.c.
Referenced by cof().
float g = (octave * 1.810)
tonne for piezo test
Definition at line 45 of file cof.c.
Referenced by cof().
float h = (2.0 * q)
Half note
Definition at line 70 of file cof.c.
Referenced by cof().
int note_display = 0
Global chooses whether to display note or not
Definition at line 80 of file cof.c.
Referenced by main(), and note().
float octave = 440.0
Fundamental freq of this octave. Ohters: 220, 440, 880, 1760
Definition at line 10 of file cof.c.
float q = 0.25
Quarter note
Definition at line 65 of file cof.c.
Referenced by cof().