Rug-warrior: /mnt/midnight/rug-warrior/libs/shared/common.c File Reference
common.c File Reference
Functions
int abs (int val)
int ap_eq (int val, int cmp, int tol)
int clip (int val, int min, int max)
int min (int a, int b)
int max (int x, int y)
void driveb (int trans, int rot)
int floor (float value)
int round (float value)
Variables
int drive_bias = 0
Function Documentation
int abs (int val)
Absolute value function for integers
Definition at line 4 of file common.c.
Referenced by ap_eq(), digits(), main(), print_diff(), sample_sound(), and therm_diff().
 {
     if(val < 0)
         return (- val);
     else
         return val;
 }
int ap_eq (int val, int cmp, int tol)
Determine if VAL is approximately equal (within TOL) of CMP
Definition at line 15 of file common.c.
References abs().
 {
     return (abs(val - cmp)) <= tol;
 }
int clip (int val, int min, int max)
Limit a VAL to the range MIN <= VAL <= MAX
Definition at line 23 of file common.c.
References max(), and min().
 {
     if(val < min)
         return min;
     else if(val > max)
         return max;
     else
         return val;
 }
void driveb (int trans, int rot)
Correct for motor bias
Definition at line 63 of file common.c.
References drive_bias, and motor().
Referenced by go_light(), and go_light_stop().
 {
     int rot_bias = (drive_bias * trans) / 100;
     motor(0,trans - (rot + rot_bias));
     motor(1,trans + (rot + rot_bias));
 }
int floor (float value)
return the loweress value (lower troncate)
Definition at line 73 of file common.c.
Referenced by round().
 {
     if(value >= 0.0) return (int)(value - 0.5);
     return (int)floor(value + 0.5);
 }
int max (int x, int y)
Find the maximum of two arguments
Definition at line 47 of file common.c.
Referenced by clip().
 {
     if(x > y)
         return x;
     else
         return y;
 }
int min (int a, int b)
Find the minimum of two arguments
Definition at line 36 of file common.c.
References a, and b.
Referenced by clip(), and light_environnement().
 {
     if(a < b)
         return a;
     else
         return b;
 }
int round (float value)
return the hihtess value (hiter troncate)
Definition at line 82 of file common.c.
References floor().
Referenced by rotate().
 {
     if(value >= 0.0) return (int)(value + 0.5);
     return (int)floor(value - 0.5);
 }
Variable Documentation
int drive_bias = 0
Open loop correction term for drive motors
Definition at line 58 of file common.c.
Referenced by driveb().