Rug-warrior: /mnt/midnight/rug-warrior/libs/shared/convert.c File Reference
convert.c File Reference
Functions
float cmToFeet (float cm)
float feetToCm (float cm)
float radToDeg (float rad)
float degToRad (float deg)
float feetToMotor (float feet, int speed)
int cmToPhotons (int distance)
int thermometer (int val, int low, int high)
int digits (int signed_val)
Variables
float PI = 3.1415956
Function Documentation
float cmToFeet (float cm)
convert cm to feet
Definition at line 6 of file convert.c.
 {
     return cm/30.48;
 }
int cmToPhotons (int distance)
Calculate the distance to stop the robot => Set prealablemently the "_light_stop_distance_" to stop (in cm) Take care of the stop distance CAUTION : If the distance it superior to will be too high the distance will be set to -1 If the more environnement is light, the less accurancy is.
Definition at line 52 of file convert.c.
References CM_TO_LIGHT_COEFFICIENT, and MAX_STOP_DISTANCE.
Referenced by go_light_stop().
 {
     if(0 > distance || distance > MAX_STOP_DISTANCE)
     {
         return 0;
     }
     return (int)((float)distance * CM_TO_LIGHT_COEFFICIENT);
 }
float degToRad (float deg)
convert degree to radian
Definition at line 30 of file convert.c.
 {
     return deg/57.2957795;
 }
int digits (int signed_val)
Count the number of digits in an integer (negative numbers add 1 for - sign)
Definition at line 89 of file convert.c.
References abs().
Referenced by printn().
 {
     int digs, val;
     val = abs(signed_val);
     if(val < 100)
     {
         if(val < 10) digs = 1;
         else digs = 2;
     }
     else if(val < 10000)
     {
         if(val < 1000) digs = 3;
         else digs = 4;
     }
     else digs = 5;
     if(signed_val >= 0) return digs;
     else return (digs + 1);
 }
float feetToCm (float cm)
convert feet to cm
Definition at line 14 of file convert.c.
Referenced by detect_distance_sonar(), and main().
 {
     return cm*30.48;
 }
float feetToMotor (float feet, int speed)
calculate the approximate time needed to run in with given speed [-100 : 100]
Definition at line 39 of file convert.c.
 {
     float tmp = (float)speed;
     float inv = 100./tmp;
     return (feet/0.67)*inv;
 }
float radToDeg (float rad)
convert radian to degree
Definition at line 22 of file convert.c.
 {
     return rad*57.2957795;
 }
int thermometer (int val, int low, int high)
calculate the difference between two value of the photo sensor and aproximate is termal value
Definition at line 65 of file convert.c.
References range().
Referenced by main().
 {
     int range = high - low;
     int blks = (((val - low) * 16) + (range >> 1)) / range;
     int j;
     if(blks < 0)
         blks = 0;
     else if(blks > 16)
         blks = 16;
     for(j = 1; j <= blks; j++)
         printf("%c",219);  /* 219 => [] */
     for(j = blks; j < 16; j++)
         printf("-");
     return blks;
 }
Variable Documentation
float PI = 3.1415956
Definition at line 1 of file convert.c.