Rug-warrior: /root/Desktop/rug-warrior/libs/music/echo.c File Reference
echo.c File Reference
Functions
void warb ()
void sample_sound ()
void capture_command ()
void twitch_aux ()
void twitch ()
void echo_control ()
void rpt ()
void start_echo ()
Variables
int sound_delta = 50
long hold_time = 175L
int loud_p = 0
int sound_count = 0
int listen_p = 1
int s_level_max = 0
float warb_low = 1500.0
float warb_high = 1600.0
float warb_dur = 0.01
int echo_cmd = 0
float cmd_period = 1.2
Function Documentation
void capture_command ()
Definition at line 83 of file echo.c.
References cmd_period, echo_cmd, sleep(), and sound_count.
Referenced by start_echo().
 {
     int old_count = 0;
     while(1)
     {
         if(old_count != sound_count)
         {
             sleep(cmd_period);    /* Wait for the sounds to happen */
             echo_cmd = sound_count;
             sound_count = 0;
         }
     }
 }
void echo_control ()
Definition at line 112 of file echo.c.
References echo_cmd, listen_p, sleep(), and warb().
Referenced by start_echo().
 {
     int i = 0;
     while(1)
     {
         if(echo_cmd != 0)
         {
             listen_p = 0;
             for(i = 0; i < echo_cmd; i++)
             {
                 warb();
                 sleep(0.2);
             }
             sleep(0.15);  /* Wait a little longer before listening again */
             echo_cmd = 0;
             listen_p = 1;
         }
     }
 }
void rpt ()
Definition at line 135 of file echo.c.
References s_level_max, sleep(), and sound_count.
Referenced by start_echo().
 {
     while(1)
     {
         printf("Echo     Cnt: %d Max sound: %d\n", sound_count, s_level_max);
         s_level_max = 0;
         sleep(0.4);
     }
 }
void sample_sound ()
Sample the microphone to see how much noise there is
Definition at line 39 of file echo.c.
References abs(), analog(), hold_time, listen_p, loud_p, microphone, s_level_max, sound_count, and sound_delta.
Referenced by start_echo().
 {
     int s_level = 0;            /* Instantaneous sound level */
     long go_low_time = 0L;
     long current_time = 0L;
     while(1)
     {
         while(listen_p)
         {
             current_time = mseconds();
             s_level = abs(analog(microphone) - 128);    /* Abs difference from 128 */
             if(s_level > s_level_max)
                 s_level_max = s_level;
             if(s_level > sound_delta)
                 go_low_time = current_time + hold_time; /* Compute new go low time */
             if(current_time > go_low_time)
                 loud_p = 0;
             else
             {
                 if(loud_p == 0)   /* Was 0, now 1 => add to transition count */
                     sound_count++;
                 loud_p = 1;
             }
         }
     }
 }
void start_echo ()
Definition at line 145 of file echo.c.
References capture_command(), echo_control(), rpt(), and sample_sound().
 {
     start_process(sample_sound());
     start_process(capture_command(),1);
     start_process(echo_control(),1);
     start_process(rpt(),1);
 }
void twitch ()
Definition at line 107 of file echo.c.
References twitch_aux().
Referenced by warb().
 {
     start_process(twitch_aux(),1);
 }
void twitch_aux ()
Definition at line 98 of file echo.c.
References drive(), and sleep().
Referenced by twitch().
 {
     drive(100,0);
     sleep(.07);
     drive(-100,0);
     sleep(0.07);
     drive(0,0);
 }
void warb ()
Definition at line 21 of file echo.c.
References beeper_off(), beeper_on(), set_beeper_pitch(), sleep(), twitch(), warb_dur, warb_high, and warb_low.
Referenced by echo_control().
 {
     float freq = warb_low;
     twitch();         /* Motion accompanies sound */
     beeper_on();
     for(freq = warb_low; freq < warb_high; freq = freq + 10.0)
     {
         set_beeper_pitch(freq);
         sleep(warb_dur);
     }
     beeper_off();
 }
Variable Documentation
float cmd_period = 1.2
This is how long we get to gather the sound
Definition at line 81 of file echo.c.
Referenced by capture_command().
int echo_cmd = 0
Count the number of low high transitions during some interval. Start a timer at the first low high transition, then keep checking for more low high transitions until time runs out
Definition at line 76 of file echo.c.
Referenced by capture_command(), and echo_control().
long hold_time = 175L
Definition at line 9 of file echo.c.
Referenced by sample_sound().
int listen_p = 1
Definition at line 13 of file echo.c.
Referenced by echo_control(), and sample_sound().
int loud_p = 0
Definition at line 10 of file echo.c.
Referenced by sample_sound().
int s_level_max = 0
Definition at line 15 of file echo.c.
Referenced by rpt(), and sample_sound().
int sound_count = 0
Definition at line 11 of file echo.c.
Referenced by capture_command(), rpt(), and sample_sound().
int sound_delta = 50
Definition at line 8 of file echo.c.
Referenced by sample_sound().
float warb_dur = 0.01
Definition at line 19 of file echo.c.
Referenced by warb().
float warb_high = 1600.0
Definition at line 18 of file echo.c.
Referenced by warb().
float warb_low = 1500.0
Definition at line 17 of file echo.c.
Referenced by warb().