Rug-warrior: /root/Desktop/rug-warrior/libs/firmware/lib_ic.c File Reference
lib_ic.c File Reference
Functions
void reset_system_time ()
float seconds ()
void sleep (float seconds)
void msleep (long msec)
void beep ()
void tone (float frequency, float length)
void beeper_on ()
void beeper_off ()
void set_beeper_pitch (float frequency)
long timer_create_mseconds (long timeout)
long timer_create_seconds (float timeout)
int timer_done (long timer)
int analog (int port)
void hog_processor ()
Variables
persistent int test_number
Function Documentation
int analog (int port)
Definition at line 161 of file lib_ic.c.
 {   poke(0x1039, 0b10000000);
     poke(0x1030, port);
     return peek(0x1031);
 }
void beep ()
Definition at line 56 of file lib_ic.c.
References tone().
 {   tone(1000., .3);    /* Old freq was 500, but 1000 sounds louder */
   }
void beeper_off ()
Definition at line 106 of file lib_ic.c.
 {
     bit_clear(0x1022, 0b00001000);
     bit_clear(0x1020, 0b00000001);
     pokeword(0x26, 0);
     bit_clear(0x1000, 0b00001000);  /* turn power to spkr off */
 }
void beeper_on ()
Definition at line 94 of file lib_ic.c.
 {
     bit_set(0x1020, 0b00000001);
     bit_set(0x1022, 0b00001000);
 }
void hog_processor ()
Definition at line 189 of file lib_ic.c.
 {
     poke(0x0a, 0);
 }
void msleep (long msec)
Definition at line 36 of file lib_ic.c.
 {
     long end_time= mseconds() + msec;
     while (1) {
     /* if the following test doesn't execute at least once a second,
        msleep may not halt */
     long done= mseconds()-end_time;
     if (done >= 0L && done <= 1000L) break;
     }
 }
void reset_system_time ()
Definition at line 18 of file lib_ic.c.
 {
   pokeword(0x14, 0);
   pokeword(0x12, 0);
 }
float seconds ()
Definition at line 26 of file lib_ic.c.
 {
   return ((float) mseconds()) / 1000.;
 }
void set_beeper_pitch (float frequency)
Definition at line 122 of file lib_ic.c.
 {
     pokeword(0x26, (int)(1E6 / frequency));
 }
void sleep (float seconds)
Definition at line 31 of file lib_ic.c.
References msleep().
 {
     msleep((long)(seconds * 1000.));
 }
long timer_create_mseconds (long timeout)
Definition at line 131 of file lib_ic.c.
 {
     return mseconds() + timeout;
 }
long timer_create_seconds (float timeout)
Definition at line 141 of file lib_ic.c.
 {
     return mseconds() + (long) (timeout * 1000.);
 }
int timer_done (long timer)
Definition at line 151 of file lib_ic.c.
 {
     return timer < mseconds();
 }
void tone (float frequency, float length)
Definition at line 66 of file lib_ic.c.
References sleep().
 {
     pokeword(0x26, (int)(1E6 / frequency));
     bit_set(0x1020, 0b00000001);
     sleep(length);
     bit_clear(0x1020, 0b00000001);
     /*  following is important to reduce # of interrupts
     when tone is off  */
     pokeword(0x26, 0);
     bit_clear(0x1000, 8);
 }
Variable Documentation
persistent int test_number
Definition at line 7 of file lib_ic.c.