Rug-warrior: /root/Desktop/rug-warrior/libs/firmware/lib_rwp.c File Reference
lib_rwp.c File Reference
Functions
int left_shaft ()
int right_shaft ()
int init_motors ()
void stop ()
void drive (int trans_vel, int rot_vel)
int bumper ()
int ir_detect ()
Variables
int photo_right = 0
int photo_left = 1
int microphone = 2
int TOCx [2] = {0x1018, 0x101A}
int dir_mask [2] = {0b00010000, 0b00100000}
int pwm_mask [2] = {0b01000000, 0b00100000}
int init_motors_dummy = init_motors()
Function Documentation
int bumper ()
Definition at line 151 of file lib_rwp.c.
References analog().
 {
     int bmpr;
     bmpr = analog(3);         /* Switch closure: */
     if(bmpr <  11) return 0b000;          /* none */
     else if(bmpr <  32) return 0b001;     /* A   */
     else if(bmpr <  53) return 0b010;     /*  B  */
     else if(bmpr <  74) return 0b011;     /* AB  */
     else if(bmpr <  96) return 0b100;     /*  C  */
     else if(bmpr < 117) return 0b101;     /* A C */
     else if(bmpr < 138) return 0b110;     /*  BC */
     else                 return 0b111;    /* ABC - (mechanically impossible) */
 }
void drive (int trans_vel, int rot_vel)
Definition at line 140 of file lib_rwp.c.
References motor().
 {
     motor(0,trans_vel - rot_vel);
     motor(1,trans_vel + rot_vel);
 }
int init_motors ()
Definition at line 99 of file lib_rwp.c.
 {
     bit_set(0x1009,0b110000); /* Set PD4,5 as outputs for motor direction */
     poke(0x100C,0b01100000);  /* OC1M Output compare 1 affects PA5,6 */
     bit_set(0x1020,0b10100000);     /* TCTL1 OC3 turns off PA5, OC2 PA6 */
     bit_clear(0x1020,0b01010000); /* Use set and clear to avoid other bits */
     pokeword(0x1016,0);       /* When TCNT = 0, OC1 fires */
 }
int ir_detect ()
Definition at line 177 of file lib_rwp.c.
References msleep().
 {
     int val1, val2, val3;
     val1 = peek(0x100A) & 0b10000;    /* IR Detector connected to PE4 */
     bit_set(0x1008,0b0100);       /* Turn on Left emitter, PD2 */
     msleep(1L);               /* Wait 1 millisecond */
     val2 = peek(0x100A) & 0b10000;    /* Should be Low if signal detected */
     bit_clear(0x1008,0b0100);     /* Turn off Left emitter */
     bit_set(0x1008,0b1000);       /* Turn on Right emitter, PD3 */
     msleep(1L);               /* Wait 1 millisecond */
     val3 = peek(0x100A) & 0b10000;
     bit_clear(0x1008,0b1100);     /* Turn emitters off */
     /* For detection, detector must be high when emitter is off, low when on */
     return ((val1 & ~val2) >> 3)  | ((val1 & ~val3) >> 4); /* HI -> LOW */
 }
int left_shaft ()
Definition at line 35 of file lib_rwp.c.
 {
     return (peek(0x1000) & 0b00000001);   /*  1  or 0 */
 }
int right_shaft ()
Definition at line 43 of file lib_rwp.c.
 {
     return (peek(0x1000) & 0b10000000 && 1);  /* 0x80 -> 1 */
 }
void stop ()
Definition at line 119 of file lib_rwp.c.
References pwm_mask.
 {
     bit_clear(0x100D,pwm_mask[0]);    /* Let OC1 turn off motors rather */
     bit_clear(0x100D,pwm_mask[1]);    /* than turn them on */
 }
Variable Documentation
int dir_mask[2] = {0b00010000, 0b00100000}
Definition at line 93 of file lib_rwp.c.
int init_motors_dummy = init_motors()
Definition at line 115 of file lib_rwp.c.
int microphone = 2
Definition at line 61 of file lib_rwp.c.
int photo_left = 1
Definition at line 59 of file lib_rwp.c.
int photo_right = 0
Definition at line 57 of file lib_rwp.c.
int pwm_mask[2] = {0b01000000, 0b00100000}
Definition at line 95 of file lib_rwp.c.
int TOCx[2] = {0x1018, 0x101A}
Definition at line 91 of file lib_rwp.c.