Rug-warrior: /root/Desktop/rug-warrior/libs/behavior/follow_light.c File Reference
follow_light.c File Reference
Macros
#define LIGHT 0
#define DARK 1
Functions
void go_light ()
void go_light_detection ()
void go_light_touch ()
void main ()
Macro Definition Documentation
#define DARK 1
Definition at line 2 of file follow_light.c.
Referenced by go_light().
#define LIGHT 0
Definition at line 1 of file follow_light.c.
Referenced by main().
Function Documentation
void go_light ()
The robot following/avoid a light infinitely mode_light if mode == LIGHT, the robot go to the light if mode == DARK, the robot go to the dark
Last update: -
Version
Final
Definition at line 12 of file follow_light.c.
References _go_light_running_, _light_environnement_, _mode_light_, _motor_initial_speed_, DARK, driveb(), light_diff(), print_diff(), and stop().
Referenced by go_light_detection(), and go_light_touch().
                 {
     _go_light_running_ = 1;
     while(_go_light_running_) {
         int diff;
         diff = light_diff();
     diff *= _light_environnement_; /* The light environnement */
         /* Invert the mode */
         if (_mode_light_ == DARK) {
             diff= -diff;
         }
         print_diff(diff);
         driveb(_motor_initial_speed_, diff);
     }
     stop();
     _go_light_running_ = -1;
 }
void go_light_detection ()
Avoid objects and go to the light or dark mode_light if mode != LIGHT, the robot go to the light if mode == DARK, the robot go to the dark
Last update: -
Version
-
Definition at line 45 of file follow_light.c.
References _go_light_detection_running_, _go_light_running_, escape(), go_light(), ir_detect(), and OBSTACLE_NONE.
{
     int ir;
     start_process(go_light());
     _go_light_detection_running_ = 1;
     while (_go_light_detection_running_) {
         /* Obstacle detected, I stop the run and I am escaping remotely */
         if ((ir = ir_detect()) != OBSTACLE_NONE) {
             _go_light_running_ = 0;
             while (_go_light_running_ != -1);
             escape(ir);
             /* Run after the correction*/
             start_process(go_light());
         }
     }
     _go_light_running_ = 0;
     while (_go_light_running_ != -1);
     _go_light_detection_running_ = -1;
 }
void go_light_touch ()
Escape objects and go to the light or dark mode_light if mode == LIGHT, the robot go to the light if mode == DARK, the robot go to the dark
Last update: -
Version
-
Definition at line 77 of file follow_light.c.
References _go_light_running_, _go_light_touch_running_, BMP_BACK, bumper_detection(), escape(), and go_light().
                       {
     int bmp;
     start_process(go_light());
     _go_light_touch_running_ = 1;
     while (_go_light_touch_running_) {
         /* Obstacle touched, I stop the run and I am escaping */
         bmp = bumper_detection();
         if (bmp != 0 && bmp != BMP_BACK) {
             _go_light_running_ = 0;
             while (_go_light_running_ != -1);
             escape(bmp);
             /* Run after the correction*/
             start_process(go_light());
         }
     }
     _go_light_running_ = 0;
     while (_go_light_running_ != -1);
     _go_light_touch_running_ = -1;
 }
void main ()
test case
Definition at line 105 of file follow_light.c.
References _light_environnement_, _mode_light_, _motor_initial_speed_, init_motors(), LIGHT, and LIGHT_ENVIRONNEMENT.
             {
     _light_environnement_ = LIGHT_ENVIRONNEMENT;
     init_motors();
     _motor_initial_speed_ = 50;
     _mode_light_ = LIGHT;
     go_light_touched();
 }