Rug-warrior: /root/Desktop/rug-warrior/libs/behavior/follow_wall2.c File Reference
follow_wall2.c File Reference
Functions
void maze_process ()
void main ()
Function Documentation
void main ()
follow the right wall on the maze can technicaly resolve the maze in a certain time Last update: -
Version
-
Definition at line 71 of file follow_wall2.c.
References _motor_left_speed_, _motor_right_speed_, _running_process_running_, BMP_BACK, bumper(), escape(), maze_process(), sleep(), stop_process, and wait_process.
 {
     int bmp;
     int pid;
     pid = start_process(maze_process());
     while(1)
     {
         bmp = bumper();
         if(bmp != BMP_BACK && bmp)
         {
             kill_process(pid);
             _motor_left_speed_ = 0;
             _motor_right_speed_ = 0;
             if(_running_process_running_ == 1)
             {
                 stop_process(_running_process_running_);
                 wait_process(_running_process_running_);
             }
             escape(bmp);
             pid = start_process(maze_process());
         }
         sleep(0.5);
     }
 }
void maze_process ()
follow the right wall on the maze can technicali resolve the maze in a certain time Last update: -
Version
-
Definition at line 7 of file follow_wall2.c.
References _motor_initial_speed_, _running_process_running_, C_MOTOR, ir_detect(), ir_previous, L_MOTOR, OBSTACLE_FRONT, OBSTACLE_LEFT, OBSTACLE_RIGHT, R_MOTOR, rotate(), running_forever(), sleep(), stop_process, and wait_process.
Referenced by main().
 {
     int ir_current;
     int ir_previous = 0;
     int light;
     int leep = 0;
     _motor_initial_speed_ = 50;
     start_process(running_forever());
     while(1)
     {
         /*
          * Depending on the ir_detect() value,
          * make it rotate, and move forward again
          */
         ir_current = ir_detect();
         /* Something is detected */
         if(ir_current != 0)
         {
             stop_process(_running_process_running_);
             wait_process(_running_process_running_);
             if(ir_current == OBSTACLE_FRONT)
             {
                 printf("FRONT\n");
                 rotate(C_MOTOR, -90*(ir_previous == OBSTACLE_RIGHT));
                 rotate(C_MOTOR,  90*(ir_previous == OBSTACLE_LEFT));
             }
             else
             {
                 printf("move out\n");
                 rotate(C_MOTOR, -30 * (ir_current == OBSTACLE_RIGHT));
                 rotate(C_MOTOR,  30 * (ir_current == OBSTACLE_LEFT));
                 ir_previous = ir_current;
             }
             start_process(running_forever());
         }
         else if(ir_previous)
         {
             printf("move to\n");
             stop_process(_running_process_running_);
             wait_process(_running_process_running_);
             rotate(L_MOTOR, 15 * (ir_previous == OBSTACLE_RIGHT));
             rotate(R_MOTOR, 15 * (ir_previous == OBSTACLE_LEFT));
             start_process(running_forever());
             sleep(0.05);
         }
     }
 }