Rug-warrior: /root/Desktop/rug-warrior/libs/firmware/lib_r22.c File Reference
lib_r22.c File Reference
Functions
void reset_system_time ()
float seconds ()
void sleep (float seconds)
void msleep (long msec)
void beep ()
void tone (float frequency, float length)
void beeper_on ()
void beeper_off ()
void set_beeper_pitch (float frequency)
void fd (int motor)
void bk (int motor)
void off (int motor)
void alloff ()
void ao ()
void motor (int m, int speed)
void _set_motor (int motor, int dir, int speed)
void _set_motor_speeds ()
void led_out1 (int s)
void led_out0 (int s)
void motor4_left (int s)
void motor4_right (int s)
void motor5_left (int s)
void motor5_right (int s)
int choose_button ()
int escape_button ()
int right_button ()
int left_button ()
int dip_switches ()
int dip_switch (int which)
int analog (int port)
int digital (int port)
int motor_force (int port)
int frob_knob ()
void hog_processor ()
void system_pwm_on ()
void system_pwm_off ()
void system_print_on ()
void system_print_off ()
Variables
int photo_right = 0
int photo_left = 1
int microphone = 2
int _motor_speed [] = {7, 7, 7, 7, 7, 7}
int _speed_table []
Function Documentation
void _set_motor (int motor, int dir, int speed)
Definition at line 250 of file lib_r22.c.
References _motor_speed, _set_motor_speeds(), and motor().
 {
     if (motor<6) {
         _motor_speed[motor]= speed;
         _set_motor_speeds();
     }
     if (motor < 4) {
         if (dir) {
             bit_set(0x0e, 0b10001 << motor);
         } else {
             bit_clear(0x0e, 1 << motor);
             bit_set(0x0e, 0b10000<<motor);
         }
     } else if (motor == 4) {
         if (dir) {
             bit_clear((int)&exp_motor_bits, 0b00010000);
             bit_set((int)&exp_motor_bits,   0b10100000);
         } else {
             bit_clear((int)&exp_motor_bits, 0b00100000);
             bit_set((int)&exp_motor_bits,   0b10010000);
         }
     } else if (motor == 5) {
         if (dir) {
             bit_clear((int)&exp_motor_bits, 0b00001000);
             bit_set((int)&exp_motor_bits,   0b01000100);
         } else {
             bit_clear((int)&exp_motor_bits, 0b00000100);
             bit_set((int)&exp_motor_bits,   0b01001000);
         }
     }
  }
void _set_motor_speeds ()
Definition at line 282 of file lib_r22.c.
References _motor_speed, and _speed_table.
 {
     int speed01= (_speed_table[_motor_speed[0]] << 8)
       + _speed_table[_motor_speed[1]];
     int speed23= (_speed_table[_motor_speed[2]] << 8)
       + _speed_table[_motor_speed[3]];
     int speed45= (_speed_table[_motor_speed[5]] << 8)
       + _speed_table[_motor_speed[4]];
     pokeword(0x22, speed01);
     pokeword(0x24, speed23);
     exp_motor_speeds= speed45;
 }
void alloff ()
Definition at line 228 of file lib_r22.c.
 {
     poke(0x0e, 0b00001010);
     bit_clear((int)&exp_motor_bits, 0b11000011);
 }
int analog (int port)
Definition at line 386 of file lib_r22.c.
References beep(), and digital().
 {
     if (port<8) /* accessing a hardware digital port */
       if (digital(port)) return 0;
       else return 255;
     if (port<12) /* accessing direct 6811 analog port */
       return analog_header_port(port);
     if (port<36) /* accessing analog port on an analog mux */
       return(read_analog(port));
     else {/* out of range */
     printf("Analog port out of range\n");
     beep();
     return -1;}
 }
void ao ()
Definition at line 234 of file lib_r22.c.
References alloff().
 {
     alloff();
 }
void beep ()
Definition at line 128 of file lib_r22.c.
References tone().
 {
     tone(500., .3);
 }
void beeper_off ()
Definition at line 148 of file lib_r22.c.
 {
     bit_clear(0x1022, 0b00001000);
     bit_clear(0x1020, 0b00000001);
     bit_clear(0x1000, 0b00001000);  /* turn power to spkr off */
 }
void beeper_on ()
Definition at line 142 of file lib_r22.c.
 {
     bit_set(0x1020, 0b00000001);
     bit_set(0x1022, 0b00001000);
 }
void bk (int motor)
Definition at line 213 of file lib_r22.c.
References _set_motor().
 {
     _set_motor(motor, (motor%2)^1, 7);
 }
int choose_button ()
Definition at line 356 of file lib_r22.c.
Referenced by left_button().
 {
     return ! (2 & (peek(0x7fff)));
 }
int digital (int port)
Definition at line 401 of file lib_r22.c.
References beep().
 {
     if (port==0) /* this is first bit of PORTA */
       return !(peek(0x1000)&1);
     if (port==1) /* this is the second bit of PORTA */
       return !(peek(0x1000)&2);
     if (port<8) /* normal bit of 7fff as gotten from digital chip */
       return !((peek(0x7fff)>>port)&1);
     if(port<36)
       return(read_analog(port)<127);
     else {
     printf("Digital port outof range\n");
     beep();
     return -1;
     }
 }
int dip_switch (int which)
Definition at line 381 of file lib_r22.c.
 {
   return(!(read_analog(27+which)<128));
 }
int dip_switches ()
Definition at line 373 of file lib_r22.c.
 {
   int i,value;
   for(i=28,value=0;i<32;i++)
     value=(value<<1) | !(read_analog(i)<128);
   return value;
 }
int escape_button ()
Definition at line 361 of file lib_r22.c.
Referenced by right_button().
 {
     return !(1 & (peek(0x7fff)));
 }
void fd (int motor)
Definition at line 208 of file lib_r22.c.
References _set_motor().
 {
     _set_motor(motor, motor%2, 7);
 }
int frob_knob ()
Definition at line 423 of file lib_r22.c.
 {
     return read_analog(32);
 }
void hog_processor ()
Definition at line 437 of file lib_r22.c.
 {
     poke(0x0a, 0);
 }
void led_out0 (int s)
Definition at line 302 of file lib_r22.c.
 {
     if (s) bit_set((int)&exp_motor_bits, 2);
     else  bit_clear((int)&exp_motor_bits, 2);
 }
void led_out1 (int s)
Definition at line 296 of file lib_r22.c.
 {
     if (s) bit_set((int)&exp_motor_bits, 1);
     else  bit_clear((int)&exp_motor_bits, 1);
 }
int left_button ()
Definition at line 368 of file lib_r22.c.
References choose_button().
 {return choose_button();}
void motor (int m, int speed)
Definition at line 239 of file lib_r22.c.
References _set_motor().
 {
   if (speed>100) speed=100;
   if (speed<-100) speed=-100;
   if (speed >= 0)
     _set_motor(m, m%2, (speed + 3) / 14);
   else
     _set_motor(m, (m%2)^1, (-speed + 3) / 14);
 }
void motor4_left (int s)
Definition at line 308 of file lib_r22.c.
References _motor_speed.
 {
     if (s) {
     bit_set  ((int)&exp_motor_bits, 0b10000000);
     bit_clear((int)&exp_motor_bits, 0b00010000);
     _motor_speed[4]= 7;
     exp_motor_speeds= (exp_motor_speeds&0xFF00) + 0xFF;
     } else
       bit_set((int)&exp_motor_bits, 0b00010000);
 }
void motor4_right (int s)
Definition at line 319 of file lib_r22.c.
References _motor_speed.
 {
     if (s) {
     bit_set  ((int)&exp_motor_bits, 0b10000000);
     bit_clear((int)&exp_motor_bits, 0b00100000);
     _motor_speed[4]= 7;
     exp_motor_speeds= (exp_motor_speeds&0xFF00) + 0xFF;
     } else
       bit_set((int)&exp_motor_bits, 0b00100000);
 }
void motor5_left (int s)
Definition at line 330 of file lib_r22.c.
References _motor_speed.
 {
     if (s) {
     bit_set  ((int)&exp_motor_bits, 0b01000000);
     bit_clear((int)&exp_motor_bits, 0b00000100);
     _motor_speed[5]= 7;
     exp_motor_speeds= (exp_motor_speeds&0xFF) + 0xFF00;
     } else
       bit_set((int)&exp_motor_bits, 0b00000100);
 }
void motor5_right (int s)
Definition at line 341 of file lib_r22.c.
References _motor_speed.
 {
     if (s) {
     bit_set  ((int)&exp_motor_bits, 0b01000000);
     bit_clear((int)&exp_motor_bits, 0b00001000);
     _motor_speed[5]= 7;
     exp_motor_speeds= (exp_motor_speeds&0xFF) + 0xFF00;
     } else
       bit_set((int)&exp_motor_bits, 0b00001000);
 }
int motor_force (int port)
Definition at line 418 of file lib_r22.c.
 {
     return analog_header_port(port+4);
 }
void msleep (long msec)
Definition at line 116 of file lib_r22.c.
 {
     long end_time= mseconds() + msec;
     while (1) {
     /* if the following test doesn't execute at least once a second,
        msleep may not halt */
     long done= mseconds()-end_time;
     if (done >= 0L && done <= 1000L) break;
     }
 }
void off (int motor)
Definition at line 218 of file lib_r22.c.
 {
     if (motor < 4)
       bit_clear(0x0e, 1 << (4 + motor));
     else if (motor == 4)
       bit_clear((int)&exp_motor_bits, 0b10000000);
     else if (motor == 5)
       bit_clear((int)&exp_motor_bits, 0b01000000);
 }
void reset_system_time ()
Definition at line 96 of file lib_r22.c.
 {
     pokeword(0x14, 0);
     pokeword(0x12, 0);
 }
int right_button ()
Definition at line 367 of file lib_r22.c.
References escape_button().
 {return escape_button();}
float seconds ()
Definition at line 107 of file lib_r22.c.
 {
     return ((float) mseconds()) / 1000.;
 }
void set_beeper_pitch (float frequency)
Definition at line 155 of file lib_r22.c.
 {
     pokeword(0x26, (int)(1E6 / frequency));
 }
void sleep (float seconds)
Definition at line 111 of file lib_r22.c.
References msleep().
 {
     msleep((long)(int)(seconds * 1000.));
 }
void system_print_off ()
Definition at line 490 of file lib_r22.c.
 {bit_clear(0x39, 0b00000001);}
void system_print_on ()
Definition at line 489 of file lib_r22.c.
 {bit_set(0x39, 0b00000001);}
void system_pwm_off ()
Definition at line 483 of file lib_r22.c.
 {bit_clear(0x39, 0b00000100);}
void system_pwm_on ()
Definition at line 482 of file lib_r22.c.
 {bit_set(0x39, 0b00000100);}
void tone (float frequency, float length)
Definition at line 134 of file lib_r22.c.
References beeper_off(), beeper_on(), set_beeper_pitch(), and sleep().
 {
     set_beeper_pitch(frequency);
     beeper_on();
     sleep(length);
     beeper_off();
 }
Variable Documentation
int _motor_speed[] = {7, 7, 7, 7, 7, 7}
Definition at line 195 of file lib_r22.c.
int _speed_table[]
Initial value:
= {
               0b00000000,
               0b00010001,
               0b01001001,
               0b01010101,
               0b01010111,
               0b01110111,
               0b01111111,
                   0b11111111
             }
Definition at line 197 of file lib_r22.c.
int microphone = 2
Definition at line 7 of file lib_r22.c.
int photo_left = 1
Definition at line 5 of file lib_r22.c.
int photo_right = 0
Definition at line 3 of file lib_r22.c.