Rug-warrior: /root/Desktop/rug-warrior/libs/firmware/lib_rw11.c File Reference
lib_rw11.c File Reference
Functions
void reset_system_time ()
float seconds ()
void sleep (float seconds)
void msleep (long msec)
void beep ()
void tone (float frequency, float length)
void beeper_on ()
void beeper_off ()
void set_beeper_pitch (float frequency)
long timer_create_mseconds (long timeout)
long timer_create_seconds (float timeout)
int timer_done (long timer)
int analog (int port)
void hog_processor ()
void dump (int addr)
int digital (int port)
int init_motors ()
void stop ()
void motor (int index, float vel)
void drive (float trans_vel, float rot_vel)
void leds (int val)
int bumper ()
int ir_detect ()
Variables
persistent int test_number
int photo_right = 0
int photo_left = 1
int microphone = 2
int pyro = 5
int TOCx [2] = {0x1018, 0x101A}
int dir_mask [2] = {0b00010000, 0b00100000}
int pwm_mask [2] = {0b01000000, 0b00100000}
int init_motors_dummy = init_motors()
Function Documentation
int analog (int port)
Definition at line 107 of file lib_rw11.c.
 {   poke(0x1039, 0b10000000);
     poke(0x1030, port);
     return peek(0x1031);
 }
void beep ()
Definition at line 52 of file lib_rw11.c.
References tone().
 {   tone(500., .3);
   }
void beeper_off ()
Definition at line 77 of file lib_rw11.c.
 {
     bit_clear(0x1022, 0b00001000);
     bit_clear(0x1020, 0b00000001);
     pokeword(0x26, 0);
     bit_clear(0x1000, 0b00001000);  /* turn power to spkr off */
 }
void beeper_on ()
Definition at line 71 of file lib_rw11.c.
 {
     bit_set(0x1020, 0b00000001);
     bit_set(0x1022, 0b00001000);
 }
int bumper ()
Definition at line 220 of file lib_rw11.c.
References analog().
 { int bmpr;
   bmpr = analog(3);         /* Switch closure: */
   if      (bmpr <  11) return 0b000;    /* none */
   else if (bmpr <  32) return 0b001;    /* A   */
   else if (bmpr <  53) return 0b010;    /*  B  */
   else if (bmpr <  74) return 0b011;    /* AB  */
   else if (bmpr <  96) return 0b100;    /*  C  */
   else if (bmpr < 117) return 0b101;    /* A C */
   else if (bmpr < 132) return 0b110;    /*  BC */
   else                 return 0b111;    /* ABC - (mechanically impossible) */
 }
int digital (int port)
Definition at line 140 of file lib_rw11.c.
 { return 1 & (peek(0x1000) >> (port & 3));
 }
void drive (float trans_vel, float rot_vel)
Definition at line 208 of file lib_rw11.c.
References motor().
 { motor(0,trans_vel - rot_vel);
   motor(1,trans_vel + rot_vel);
 }
void dump (int addr)
Definition at line 129 of file lib_rw11.c.
 { printf("%x: %x %x ", addr, peekword(addr), peekword(addr + 2));
   printf("      %x %x\n",  peekword(addr + 4), peekword(addr + 6));
 }
void hog_processor ()
Definition at line 121 of file lib_rw11.c.
 {
     poke(0x0a, 0);
 }
int init_motors ()
Definition at line 169 of file lib_rw11.c.
 { bit_set(0x1009,0b110000); /* Set PD4,5 as outputs for motor direction */
   poke(0x100C,0b01100000);  /* OC1M Output compare 1 affects PA5,6 */
   bit_set(  0x1020,0b10100000); /* TCTL1 OC3 turns off PA5, OC2 PA6 */
   bit_clear(0x1020,0b01010000); /* Use set and clear to avoid other bits */
   pokeword(0x1018,0);       /* When TCNT = 0, OC1 fires */
 }
int ir_detect ()
Definition at line 237 of file lib_rw11.c.
References msleep().
 { int val1, val2, val3;
   val1 = peek(0x100A) & 0b10000;    /* IR Detector connected to PE4 */
   bit_set(0x1008,0b1000);       /* Turn on Left emitter, PD3 */
   msleep(1L);               /* Wait 1 millisecond */
   val2 = peek(0x100A) & 0b10000;    /* Should be Low if signal detected */
   bit_clear(0x1008,0b1000);     /* Turn off Left emitter */
   bit_set(0x1008,0b0100);       /* Turn on Right emitter, PD2 */
   msleep(1L);               /* Wait 1 millisecond */
   val3 = peek(0x100A) & 0b10000;
   bit_clear(0x1008,0b1100);     /* Turn emitters off */
   /* For detection, detector must be high when emitter is off, low when on */
   return ((val1 & ~val2) >> 3)  | ((val1 & ~val3) >> 4); /* HI -> LOW */
 }
void leds (int val)
Definition at line 214 of file lib_rw11.c.
 { poke(0x1009,0b111100);    /* Set port D for output */
   poke(0x1008,val << 2);    /* Shift number over */
 }
void motor (int index, float vel)
Definition at line 188 of file lib_rw11.c.
References dir_mask, pwm_mask, and TOCx.
 { float avel    ;   /* Absolute value of velocity */
   if (vel > 0.0)
     { bit_set(0x1008, dir_mask[index]); /* Forward rotation */
       avel = vel; }
   else
     { bit_clear(0x1008, dir_mask[index]); /* Backward rotation */
       avel = (- vel); }
   if (avel < 1.0)       /* If we are going real slow */
     bit_clear(0x100D,pwm_mask[index]);  /* then just have OC1 turn off the motor */
   else
     bit_set(0x100D,pwm_mask[index]);    /* Otherwise let OC1 control the motors */
   if (avel > 99.0)      /* If we are gong real fast */
     avel = 99.0;        /* don't let the following multiply overflow */
   pokeword(TOCx[index], (int) (655.56 * avel)); /* Compute TOCx value */
 }
void msleep (long msec)
Definition at line 40 of file lib_rw11.c.
 {
     long end_time= mseconds() + msec;
     while (1) {
     /* if the following test doesn't execute at least once a second,
        msleep may not halt */
     long done= mseconds()-end_time;
     if (done >= 0L && done <= 1000L) break;
     }
 }
void reset_system_time ()
Definition at line 23 of file lib_rw11.c.
 {
   pokeword(0x14, 0);
   pokeword(0x12, 0);
 }
float seconds ()
Definition at line 30 of file lib_rw11.c.
 {
   return ((float) mseconds()) / 1000.;
 }
void set_beeper_pitch (float frequency)
Definition at line 85 of file lib_rw11.c.
 {
     pokeword(0x26, (int)(1E6 / frequency));
 }
void sleep (float seconds)
Definition at line 35 of file lib_rw11.c.
References msleep().
 {
     msleep((long)(seconds * 1000.));
 }
void stop ()
Definition at line 181 of file lib_rw11.c.
References pwm_mask.
 { bit_clear(0x100D,pwm_mask[0]);    /* Let OC1 turn off motors rather */
   bit_clear(0x100D,pwm_mask[1]);    /* than turn them on */
 }
long timer_create_mseconds (long timeout)
Definition at line 90 of file lib_rw11.c.
 {
     return mseconds() + timeout;
 }
long timer_create_seconds (float timeout)
Definition at line 95 of file lib_rw11.c.
 {
     return mseconds() + (long) (timeout * 1000.);
 }
int timer_done (long timer)
Definition at line 100 of file lib_rw11.c.
 {
     return timer < mseconds();
 }
void tone (float frequency, float length)
Definition at line 57 of file lib_rw11.c.
References sleep().
 {
     pokeword(0x26, (int)(1E6 / frequency));
     bit_set(0x1020, 0b00000001);
     sleep(length);
     bit_clear(0x1020, 0b00000001);
     /*  following is important to reduce # of interrupts
     when tone is off  */
     pokeword(0x26, 0);
     bit_clear(0x1000, 8);
 }
Variable Documentation
int dir_mask[2] = {0b00010000, 0b00100000}
Definition at line 166 of file lib_rw11.c.
int init_motors_dummy = init_motors()
Definition at line 179 of file lib_rw11.c.
int microphone = 2
Definition at line 149 of file lib_rw11.c.
int photo_left = 1
Definition at line 148 of file lib_rw11.c.
int photo_right = 0
Definition at line 147 of file lib_rw11.c.
int pwm_mask[2] = {0b01000000, 0b00100000}
Definition at line 167 of file lib_rw11.c.
int pyro = 5
Definition at line 150 of file lib_rw11.c.
persistent int test_number
Definition at line 12 of file lib_rw11.c.
int TOCx[2] = {0x1018, 0x101A}
Definition at line 165 of file lib_rw11.c.