Rug-warrior: /root/Desktop/rug-warrior/libs/firmware/lib_rw10.c File Reference
lib_rw10.c File Reference
Functions
int init_on_load ()
void frob (int loc, int bits)
void reset_system_time ()
float seconds ()
void sleep (float seconds)
void msleep (long msec)
void beep ()
void tone (float frequency, float length)
void beeper_on ()
void beeper_off ()
void set_beeper_pitch (float frequency)
long timer_create_mseconds (long timeout)
long timer_create_seconds (float timeout)
int timer_done (long timer)
void init_motors ()
void fd (int m)
void bk (int m)
void off (int m)
void alloff ()
void ao ()
void motor (int m, int speed)
int digital (int port)
int analog (int port)
void timer2 (int on)
void timer3 (int on)
void hog_processor ()
void system_pwm_on ()
void system_pwm_off ()
Variables
int _foobar = init_on_load()
int _speed_table []
int port_a = 0x1000
int port_d = 0x1008
Function Documentation
void alloff ()
Definition at line 205 of file lib_rw10.c.
References ao().
 {
     ao();
 }
int analog (int port)
Definition at line 241 of file lib_rw10.c.
 {
     poke(0x1039, 0b10000000);
     poke(0x1030, port);
     return peek(0x1031);
 }
void ao ()
Definition at line 210 of file lib_rw10.c.
References off().
 {
     off(0);
     off(1);
 }
void beep ()
Definition at line 71 of file lib_rw10.c.
References tone().
 {
     tone(500., .3);
 }
void beeper_off ()
Definition at line 97 of file lib_rw10.c.
 {
     bit_clear(0x1022, 0b00001000);
     bit_clear(0x1020, 0b00000001);
     pokeword(0x26, 0);
     bit_clear(0x1000, 0b00001000);  /* turn power to spkr off */
 }
void beeper_on ()
Definition at line 91 of file lib_rw10.c.
 {
     bit_set(0x1020, 0b00000001);
     bit_set(0x1022, 0b00001000);
 }
void bk (int m)
Definition at line 195 of file lib_rw10.c.
References motor().
 {
     motor(m, -100);
 }
int digital (int port)
Definition at line 233 of file lib_rw10.c.
 {
     if (port > 1)
       return 1 & (peek(0x7fff) >> port);
     else
       return 1 & (peek(0x1000) >> port);
 }
void fd (int m)
Definition at line 190 of file lib_rw10.c.
References motor().
 {
     motor(m, 100);
 }
void frob (int loc, int bits)
Definition at line 23 of file lib_rw10.c.
References sleep().
 {
     while (1) {
     sleep(.1);
     bit_set  (loc, bits);
     sleep(.1);
     bit_clear(loc, bits);
     }
 }
void hog_processor ()
Definition at line 279 of file lib_rw10.c.
 {
     poke(0x0a, 0);
 }
void init_motors ()
Definition at line 184 of file lib_rw10.c.
 {
     bit_set(0x1026, 0b00001000);
     poke(0x1009, 0b00111110);
 }
int init_on_load ()
Definition at line 15 of file lib_rw10.c.
References init_motors().
 {
     /* Functions to be called when this module is -loaded- */
    init_motors();
 }
void motor (int m, int speed)
Definition at line 216 of file lib_rw10.c.
References _speed_table, and port_d.
 {
     if (m==0 || m==1) {
     if (speed >= 0) {
         bit_set(port_d, (0b00010000 << m));  /* set direction */
         poke(0x22+m, _speed_table[(speed+7)/14]);
     }
     else {
         bit_clear(port_d, (0b00010000 << m)); /* set direction */
         poke(0x22+m, _speed_table[(7-speed)/14]);
     }
     }
 }
void msleep (long msec)
Definition at line 59 of file lib_rw10.c.
 {
     long end_time= mseconds() + msec;
     while (1) {
     /* if the following test doesn't execute at least once a second,
        msleep may not halt */
     long done= mseconds()-end_time;
     if (done >= 0L && done <= 1000L) break;
     }
 }
void off (int m)
Definition at line 200 of file lib_rw10.c.
References motor().
 {
     motor(m, 0);
 }
void reset_system_time ()
Definition at line 42 of file lib_rw10.c.
 {
   pokeword(0x14, 0);
     pokeword(0x12, 0);
 }
float seconds ()
Definition at line 49 of file lib_rw10.c.
 {
     return ((float) mseconds()) / 1000.;
 }
void set_beeper_pitch (float frequency)
Definition at line 105 of file lib_rw10.c.
 {
     pokeword(0x26, (int)(1E6 / frequency));
 }
void sleep (float seconds)
Definition at line 54 of file lib_rw10.c.
References msleep().
 {
     msleep((long)(seconds * 1000.));
 }
void system_pwm_off ()
Definition at line 304 of file lib_rw10.c.
 {bit_clear(0x39, 0b00000100);}
void system_pwm_on ()
Definition at line 303 of file lib_rw10.c.
 {bit_set(0x39, 0b00000100);}
void timer2 (int on)
Definition at line 252 of file lib_rw10.c.
 {
     if (on)
       bit_set (0x1000, 0b01000000);
     else
       bit_clear (0x1000, 0b01000000);
 }
void timer3 (int on)
Definition at line 261 of file lib_rw10.c.
 {
     if (on)
       bit_set (0x1000, 0b00100000);
     else
       bit_clear (0x1000, 0b00100000);
 }
long timer_create_mseconds (long timeout)
Definition at line 111 of file lib_rw10.c.
 {
     return mseconds() + timeout;
 }
long timer_create_seconds (float timeout)
Definition at line 116 of file lib_rw10.c.
 {
     return mseconds() + (long) (timeout * 1000.);
 }
int timer_done (long timer)
Definition at line 121 of file lib_rw10.c.
 {
     return timer < mseconds();
 }
void tone (float frequency, float length)
Definition at line 77 of file lib_rw10.c.
References sleep().
 {
     pokeword(0x26, (int)(1E6 / frequency));
     bit_set(0x1020, 0b00000001);
     sleep(length);
     bit_clear(0x1020, 0b00000001);
     /*  following is important to reduce # of interrupts
     when tone is off  */
     pokeword(0x26, 0);
     bit_clear(0x1000, 8);
 }
Variable Documentation
int _foobar = init_on_load()
Definition at line 21 of file lib_rw10.c.
int _speed_table[]
Initial value:
= {
                   0b00000000,
               0b00010001,
               0b01001001,
               0b01010101,
               0b01010111,
               0b01110111,
               0b01111111,
                   0b11111111
             }
Definition at line 170 of file lib_rw10.c.
int port_a = 0x1000
Definition at line 181 of file lib_rw10.c.
int port_d = 0x1008
Definition at line 182 of file lib_rw10.c.
Referenced by motor().