Rug-warrior: /root/Desktop/rug-warrior/libs/firmware/lib_hb.c File Reference
lib_hb.c File Reference
Functions
void reset_system_time ()
float seconds ()
void sleep (float seconds)
void msleep (long msec)
void beep ()
void tone (float frequency, float length)
void beeper_on ()
void beeper_off ()
void set_beeper_pitch (float frequency)
void fd (int motor)
void bk (int motor)
void off (int motor)
void alloff ()
void ao ()
void motor (int m, int speed)
void _set_motor (int motor, int dir, int speed)
void _set_motor_speeds ()
int stop_button ()
int start_button ()
void start_press ()
void stop_press ()
int analog (int port)
int _raw_analog (int port)
int digital (int port)
int knob ()
void hog_processor ()
void system_pwm_on ()
void system_pwm_off ()
void system_print_on ()
void system_print_off ()
int random (int mod)
Variables
int _motor_speed [] = {7, 7, 7, 7, 7, 7}
int _speed_table []
Function Documentation
int _raw_analog (int port)
Definition at line 313 of file lib_hb.c.
Referenced by analog(), and knob().
 {
     poke(0x1039, 0b10000000);
     poke(0x1030, port);
     return peek(0x1031);
 }
void _set_motor (int motor, int dir, int speed)
Definition at line 245 of file lib_hb.c.
References _motor_speed, _set_motor_speeds(), and motor().
Referenced by bk(), fd(), and motor().
 {
     bit_set(0x0e, 1 << (4 + motor));    /* turn motor on */
     if (dir)
     bit_set(0x0e, 1 << motor);  /* set direction for backward */
     else
     bit_clear(0x0e, 1 << motor);    /* set dir for forward */
     _motor_speed[motor]= speed;
     _set_motor_speeds();
 }
void _set_motor_speeds ()
Definition at line 256 of file lib_hb.c.
References _motor_speed, and _speed_table.
Referenced by _set_motor().
 {
     int speed01= (_speed_table[_motor_speed[0]] << 8)
       + _speed_table[_motor_speed[1]];
     int speed23= (_speed_table[_motor_speed[2]] << 8)
       + _speed_table[_motor_speed[3]];
     pokeword(0x22, speed01);
     pokeword(0x24, speed23);
 }
void alloff ()
Definition at line 224 of file lib_hb.c.
Referenced by ao().
 {
     poke(0x0e, 0b0000000);
 }
int analog (int port)
Definition at line 295 of file lib_hb.c.
References _raw_analog(), beep(), and digital().
 {
     if (port < 7)
     {
         return _raw_analog(port);
     }
     else if (port < 16)
     {
         return 255 * !digital(port);
     }
     else
     {
         printf("Analog port out of range\n");
         beep();
         return -1;
     }
 }
void ao ()
Definition at line 229 of file lib_hb.c.
References alloff().
Referenced by alloff().
 {
     alloff();
 }
void beep ()
Definition at line 129 of file lib_hb.c.
References tone().
 {
     tone(500., .1);
 }
void beeper_off ()
Definition at line 149 of file lib_hb.c.
 {
     bit_clear(0x1022, 0b00001000);
     bit_clear(0x1020, 0b00000001);
     bit_clear(0x1000, 0b00001000);  /* turn power to spkr off */
 }
void beeper_on ()
Definition at line 143 of file lib_hb.c.
 {
     bit_set(0x1020, 0b00000001);
     bit_set(0x1022, 0b00001000);
 }
void bk (int motor)
Definition at line 214 of file lib_hb.c.
References _set_motor().
 {
     _set_motor(motor, 1, 7);
 }
int digital (int port)
Definition at line 320 of file lib_hb.c.
References analog(), and beep().
 {
     if (port < 7) /* analogs */
         return analog(port) < 255;
     if (port == 7) /* TIC1 */
         return !(peek(0x1000) & 1);
     if (port == 8) /* TIC2 */
         return !(peek(0x1000) & 2);
     if (port == 9) /* PAI */
         return !(peek(0x1000) & 128);
     if (port < 16) /* normal bit of 7fff as gotten from digital chip */
       return !((peek(0x7fff) >> (port - 10)) & 1);
     else {
     printf("Digital port outof range\n");
     beep();
     return -1;
     }
 }
void fd (int motor)
Definition at line 209 of file lib_hb.c.
References _set_motor().
 {
     _set_motor(motor, 0, 7);
 }
void hog_processor ()
Definition at line 352 of file lib_hb.c.
 {
     poke(0x0a, 0);
 }
int knob ()
Definition at line 339 of file lib_hb.c.
References _raw_analog().
 {
     return _raw_analog(7);
 }
void motor (int m, int speed)
Definition at line 234 of file lib_hb.c.
References _set_motor().
 {
   if (speed>100) speed=100;
   if (speed<-100) speed=-100;
   if (speed >= 0)
     _set_motor(m, 0, (speed + 3) / 14);
   else
     _set_motor(m, 1, (-speed + 3) / 14);
 }
void msleep (long msec)
Definition at line 117 of file lib_hb.c.
 {
     long end_time= mseconds() + msec;
     while (1) {
     /* if the following test doesn't execute at least once a second,
        msleep may not halt */
     long done= mseconds()-end_time;
     if (done >= 0L && done <= 1000L) break;
     }
 }
void off (int motor)
Definition at line 219 of file lib_hb.c.
Referenced by ao().
 {
     bit_clear(0x0e, 1 << (4 + motor));
 }
int random (int mod)
Definition at line 410 of file lib_hb.c.
 {
     return (peekword(0x100e) & 0x7fff) % mod;
 }
void reset_system_time ()
Definition at line 97 of file lib_hb.c.
 {
     pokeword(0x14, 0);
     pokeword(0x12, 0);
 }
float seconds ()
Definition at line 108 of file lib_hb.c.
 {
     return ((float) mseconds()) / 1000.;
 }
void set_beeper_pitch (float frequency)
Definition at line 156 of file lib_hb.c.
 {
     pokeword(0x26, (int)(1E6 / frequency));
 }
void sleep (float seconds)
Definition at line 112 of file lib_hb.c.
References msleep().
 {
     msleep((long)(int)(seconds * 1000.));
 }
int start_button ()
Definition at line 276 of file lib_hb.c.
Referenced by start_press().
 {
     return ! (0x80 & (peek(0x7fff)));
 }
void start_press ()
Definition at line 281 of file lib_hb.c.
References beep(), and start_button().
 {
     while (!start_button());
     while (start_button());
     beep();
 }
int stop_button ()
Definition at line 271 of file lib_hb.c.
Referenced by stop_press().
 {
     return ! (0x40 & (peek(0x7fff)));
 }
void stop_press ()
Definition at line 288 of file lib_hb.c.
References beep(), and stop_button().
 {
     while (!stop_button());
     while (stop_button());
     beep();
 }
void system_print_off ()
Definition at line 405 of file lib_hb.c.
 {bit_clear(0x39, 0b00000001);}
void system_print_on ()
Definition at line 404 of file lib_hb.c.
 {bit_set(0x39, 0b00000001);}
void system_pwm_off ()
Definition at line 398 of file lib_hb.c.
 {bit_clear(0x39, 0b00000100);}
void system_pwm_on ()
Definition at line 397 of file lib_hb.c.
 {bit_set(0x39, 0b00000100);}
void tone (float frequency, float length)
Definition at line 135 of file lib_hb.c.
References beeper_off(), beeper_on(), set_beeper_pitch(), and sleep().
 {
     set_beeper_pitch(frequency);
     beeper_on();
     sleep(length);
     beeper_off();
 }
Variable Documentation
int _motor_speed[] = {7, 7, 7, 7, 7, 7}
Definition at line 196 of file lib_hb.c.
Referenced by _set_motor(), _set_motor_speeds(), motor4_left(), motor4_right(), motor5_left(), and motor5_right().
int _speed_table[]
Initial value:
= {
               0b00000000,
               0b00010001,
               0b01001001,
               0b01010101,
               0b01010111,
               0b01110111,
               0b01111111,
                   0b11111111
             }
Definition at line 198 of file lib_hb.c.
Referenced by _set_motor_speeds(), and motor().