Rug-warrior: /root/Desktop/rug-warrior/libs/behavior/ligth_stop.c File Reference
ligth_stop.c File Reference
Functions
void main ()
Function Documentation
void main ()
Always run but stop when a ligth is detected (20cm) and adjust his distance to
Last update: -
Version
-
Definition at line 9 of file ligth_stop.c.
References _detect_distance_process_running_, _move_behind_detected_distance_, detect_distance_sonar(), feetToCm(), init_motors(), init_sonar(), move_behind(), ping(), range(), set_servo(), sleep(), sonar_init_servo(), and sonar_servo_off().
 {
     init_motors();
     init_sonar();
     sonar_init_servo();
     printf("Follow a light source 20 cm away\n");
     set_servo(0);
     sleep(0.175);
     ping();
     _move_behind_detected_distance_ = feetToCm(range());
     start_process(detect_distance_sonar());
     move_behind(20.0, 1.0, 30);
     _detect_distance_process_running_ = 0;
     while(_detect_distance_process_running_ != 1);
     set_servo(0);
     sonar_servo_off();
 }