Rug-warrior: /mnt/midnight/rug-warrior/libs/behavior/maze.c File Reference
maze.c File Reference
Functions
void maze_process ()
void main ()
Variables
int ir_previous = 0
Function Documentation
void main ()
follow the right wall on the maze can technicali resolve the maze in a certain time Last update: -
Version
-
Definition at line 114 of file maze.c.
References _motor_left_speed_, _motor_right_speed_, _running_process_running_, bumper_detection(), drive(), escape(), ir_previous, join_process, maze_process(), and sleep().
 {
     int bmp;
     int pid;
     pid = start_process(maze_process());
     while(1)
     {
         bmp = bumper_detection();
         if(bmp)
         {
             kill_process(pid);
             _motor_right_speed_ = 0;
             _motor_left_speed_ = 0;
             join_process(_running_process_running_);
             drive(-50,0);
             sleep(0.50);
             if(ir_previous)
                 escape(ir_previous);
             else
                 escape(bmp);
             pid = start_process(maze_process());
         }
         sleep(0.5);
     }
 }
void maze_process ()
Definition at line 10 of file maze.c.
References _motor_initial_speed_, _running_process_running_, C_MOTOR, init_sonar(), ir_detect(), ir_previous, L_MOTOR, OBSTACLE_FRONT, OBSTACLE_LEFT, OBSTACLE_RIGHT, R_MOTOR, rotate(), running_forever(), sleep(), sonar_init_servo(), stop_process, timer_create_mseconds(), timer_done(), and wait_process.
Referenced by main().
 {
     int ir_current;
     int ir_tmp;
     long timer = 0L;
     init_sonar();
     sonar_init_servo();
     _motor_initial_speed_ = 50;
     start_process(running_forever());
     sleep(0.2);
     while(1)
     {
         /*
          * Depending on the ir_detect() value,
          * make it rotate, and move forward again
          */
         ir_current = ir_detect();
         /* Something is detected */
         if(ir_current != 0)
         {
             stop_process(_running_process_running_);
             wait_process(_running_process_running_);
             if(ir_current == OBSTACLE_FRONT)
             {
                 printf("FRONT\n");
                 if(timer_done(timer) || timer == 0L)
                 {
                     rotate(C_MOTOR, -70*(ir_previous == OBSTACLE_RIGHT));
                     rotate(C_MOTOR,  70*(ir_previous != OBSTACLE_RIGHT));
                     timer = timer_create_mseconds(1000L);
                 }
                 else
                 {
                     /*
                      * if two consecutive front was detected
                      * then rotate
                      */
                     ir_tmp = ir_detect();
                     if(ir_tmp == OBSTACLE_FRONT)
                     {
                         rotate(C_MOTOR,  140*(ir_previous == OBSTACLE_RIGHT));
                         rotate(C_MOTOR, -140*(ir_previous != OBSTACLE_RIGHT));
                     }
                     /*
                      * if three consecutive front was detected
                      * then rotate
                      */
                     ir_tmp = ir_detect();
                     if(ir_tmp == OBSTACLE_FRONT)
                     {
                         rotate(C_MOTOR, -250*(ir_previous == OBSTACLE_RIGHT));
                         rotate(C_MOTOR,  250*(ir_previous != OBSTACLE_RIGHT));
                     }
                     timer = timer_create_mseconds(500L);
                 }
                 ir_previous = 0;
             }
             else
             {
                 printf("move out\n");
                 rotate(C_MOTOR, -30 * (ir_current == OBSTACLE_RIGHT));
                 rotate(C_MOTOR,  30 * (ir_current == OBSTACLE_LEFT));
                 ir_previous = ir_current;
             }
             start_process(running_forever());
         }
         else if(ir_previous)
         {
             printf("move to\n");
             stop_process(_running_process_running_);
             wait_process(_running_process_running_);
             rotate(L_MOTOR, 10 * (ir_previous == OBSTACLE_RIGHT));
             rotate(R_MOTOR, 10 * (ir_previous == OBSTACLE_LEFT));
             start_process(running_forever());
             sleep(0.175);
         }
     }
 }
Variable Documentation
int ir_previous = 0
Definition at line 8 of file maze.c.
Referenced by main(), and maze_process().