Rug-warrior: /mnt/midnight/rug-warrior/libs/shared/photo_cell.c File Reference
photo_cell.c File Reference
Functions
int light_diff ()
void light_environnement ()
void display_info ()
Function Documentation
void display_info ()
Display values of photo cells once time
Definition at line 43 of file photo_cell.c.
References analog(), p_byte(), photo_left, photo_right, and print_diff().
 {
     int pc_left, pc_right;
     pc_left  = analog(photo_left);
     pc_right = analog(photo_right);
     /* Diff thermometer points toward brighter light */
     print_diff(pc_left - pc_right);
     printf("Photo L");
     p_byte(pc_left);
     printf(" R");
     p_byte(pc_right);
     printf(" \n");
 }
int light_diff ()
Calculate the difference between photos cells
Returns
-100 (absolute light in left, with absolute dark in the right) to 100 (absolute light in right, with absolute dark in the left)
Definition at line 6 of file photo_cell.c.
References analog(), photo_left, and photo_right.
Referenced by go_light(), go_light_stop(), and main().
 {
     int pc_left, pc_right;
     pc_left  = analog(photo_left); /* 0 to 255 */
     pc_right = analog(photo_right); /* 0 to 255 */
     return (int)((float)(pc_right - pc_left) /2.55);
 }
void light_environnement ()
Ajust the global variable "_light_environnement_" with the environnement light
Definition at line 17 of file photo_cell.c.
References _light_environnement_, analog(), DARK_ENVIRONNEMENT, LIGHT_ENVIRONNEMENT, min(), photo_left, photo_right, VDARK_ENVIRONNEMENT, and VLIGHT_ENVIRONNEMENT.
Referenced by go_light_stop_touch(), and main().
 {
     int lightest = min(analog(photo_left), analog(photo_right)); /* 0 to 255 */
     if(lightest < 32)
     {
         _light_environnement_ = VLIGHT_ENVIRONNEMENT;
     }
     else if(lightest < 64)
     {
         _light_environnement_ = LIGHT_ENVIRONNEMENT;
     }
     else if(lightest < 128)
     {
         _light_environnement_ = DARK_ENVIRONNEMENT;
     }
     else
     {
         _light_environnement_ = VDARK_ENVIRONNEMENT;
     }
 }