Rug-warrior: /root/Desktop/rug-warrior/libs/test/photo.c File Reference
photo.c File Reference
Functions
void p_byte (int val)
void therm_diff (int val)
void main ()
Function Documentation
void main ()
always print the photo state (left, rigth) and the difference value
Definition at line 40 of file photo.c.
References analog(), p_byte(), photo_left, photo_right, sleep(), and therm_diff().
 {
     int pc_left, pc_right;
     while(1)
     {
         pc_left  = analog(photo_left);
         pc_right = analog(photo_right);
         /* Diff thermometer points toward brighter light */
         therm_diff(pc_left - pc_right);
         printf("Photo L");
         p_byte(pc_left);
         printf(" R");
         p_byte(pc_right);
         printf(" \n");
         sleep(0.25);
     }
 }
void p_byte (int val)
Definition at line 1 of file photo.c.
Referenced by main().
 {
     if(val < 10)
         printf("  %d", val);
     else if(val < 100)
         printf(" %d", val);
     else
         printf("%d", val);
 }
void therm_diff (int val)
therm_diff is for displaying the difference between two quantities
Definition at line 14 of file photo.c.
References abs(), and repeat_char().
Referenced by main().
 {
     if(val == 0)
         printf("       []       "); /* Zero */
     else if(val < -8)
         printf("%c<<<<<<<]       ",127);    /* Less than -8 */
     else if(val < 0)
     {
         repeat_char(32,8 + val);  /* 32 = space */
         repeat_char(60,abs(val)); /* 60 = "<" */
         printf("]       ");
     }
     else if(val > 8)
         printf("       [>>>>>>>%c",126);    /* More than +8 */
     else
     {
         printf("       [");
         repeat_char(62,val);
         repeat_char(32,8 - val);
     }
 }