Rug-warrior: /mnt/midnight/rug-warrior/libs/behavior/rotate.c File Reference
rotate.c File Reference
Macros
#define SLEEP 2.
Functions
void rotate_test_all_for (int degree)
void main ()
Macro Definition Documentation
#define SLEEP 2.
Definition at line 1 of file rotate.c.
Referenced by rotate_test_all_for().
Function Documentation
void main ()
Definition at line 40 of file rotate.c.
References _motor_initial_speed_, init_motors(), and rotate_test_all_for().
 {
     init_motors();
     _motor_initial_speed_ = 50;
     printf("Rotate sample using %d speed\n", _motor_initial_speed_);
     rotate_test_all_for(45);
     rotate_test_all_for(90);
     rotate_test_all_for(180);
     /*rotate_test_all_for(270);*/
     rotate_test_all_for(360);
     printf("end\n");
 }
void rotate_test_all_for (int degree)
Definition at line 7 of file rotate.c.
References C_MOTOR, rotate(), SLEEP, and sleep().
 {
     printf("Center %d\n", degree);
     rotate(C_MOTOR, degree);
     sleep(SLEEP);
     printf("Inv center %d\n", -degree);
     rotate(C_MOTOR, -degree);
     sleep(SLEEP);
 /*
     printf("Left %d\n", degree);
     rotate(L_MOTOR, degree);
     sleep(SLEEP);
     printf("Inv left %d\n", -degree);
     rotate(L_MOTOR, -degree);
     sleep(SLEEP);
     printf("Right %d\n", degree);
     rotate(R_MOTOR, degree);
     sleep(1.);
     printf("Inv right %d\n", -degree);
     rotate(R_MOTOR, -degree);
     sleep(SLEEP);
 */
 }