Rug-warrior: /mnt/midnight/rug-warrior/libs/shared/screen.c File Reference
screen.c File Reference
Functions
void printn (int val, int cols)
void repeat_char (int ch, int rep)
void p_byte (int val)
void print_diff (int diff)
Function Documentation
void p_byte (int val)
Display a value with a constant number of digits => " 1" OR " 10" OR "100"
Definition at line 35 of file screen.c.
Referenced by display_info(), and main().
 {
     if(val < 10)
         printf("  %d", val);
     else if(val < 100)
         printf(" %d", val);
     else
         printf("%d", val);
 }
void print_diff (int diff)
Display a difference proportionately Can be used to show a difference between 2 captors
Parameters
diff - difference
Definition at line 50 of file screen.c.
References abs(), and repeat_char().
Referenced by display_info(), and go_light().
 {
     if(diff == 0)
         printf("       []       "); /* Zero */
     else if(diff < -8)
         printf("%c<<<<<<<]       ",127);    /* Less than -8 */
     else if(diff < 0)
     {
         repeat_char(32,8 + diff);  /* 32 = space */
         repeat_char(60,abs(diff)); /* 60 = "<" */
         printf("]       ");
     }
     else if(diff > 8)
         printf("       [>>>>>>>%c",126);    /* More than +8 */
     else
     {
         printf("       [");
         repeat_char(62,diff);
         repeat_char(32,8 - diff);
     }
 }
void printn (int val, int cols)
Print val in the given number of columns if possible
Definition at line 5 of file screen.c.
References digits(), and repeat_char().
Referenced by display_mot_test(), and main().
 {
     int digs;
     digs = digits(val);
     /* May not be possible to print in required number of cols */
     if(digs >= cols)
         printf("%d", val);
     else
     {
         repeat_char(32,cols - digs);
         printf("%d",val);
     }
 }
void repeat_char (int ch, int rep)
repeat ch on rep column
Definition at line 24 of file screen.c.
Referenced by print_diff(), printn(), and therm_diff().
 {
     int j = 0;
     for(j = 0; j < rep; j++)
         printf("%c", ch);
 }