Rug-warrior: /root/Desktop/rug-warrior/libs/shared/sonar.c File Reference
sonar.c File Reference
Functions
void init_sonar ()
void ping ()
float range ()
void sonar_enable_servo ()
void sonar_disable_servo ()
void sonar_init_servo ()
void sonar_servo_off ()
void pwm_servo (int usec)
void set_servo (int pos)
void scan (int low_pos, int high_pos)
void scan_display_position (int low_pos, int high_pos, int nLoop)
Variables
int RugBat_jumper = 0
int RugBat_addr = 0x4000 + (RugBat_jumper * 0x1000)
int _tctl1 = 0x1020
int _tctl2 = 0x1021
int _tflg1 = 0x1023
int _oc1m = 0x100C
int _oc1d = 0x100D
int _toc1 = 0x1016
int _toc5 = 0x101E
int _tic1 = 0x1010
int _tic2 = 0x1012
int servo_pos = 0
float scan_delay = 0.01
int servo_center = 1475
int servo_gain = 10
Function Documentation
void init_sonar ()
Enable input capture of rising edge waveforms on lines PA1 and PA2. init_sonar() must be called before ping().
Definition at line 60 of file sonar.c.
References _tctl2, and beeper_off().
Referenced by main().
 {
     beeper_off();
     bit_set(_tctl2,0b010100); /* Use bit_set and bit_clear rather than */
     bit_clear(_tctl2,0b101000);   /* poke to avoid changing other tctl2 bits */
 }
void ping ()
Initiate a sonar pulse. init_sonar must be called before a ping can be sent.
Definition at line 71 of file sonar.c.
References _tflg1, RugBat_addr, and sleep().
Referenced by detect_distance_sonar(), and main().
 {
     poke(_tflg1,0b10);        /* Writing 1 clears echo received flag */
     bit_set(RugBat_addr,0b001);   /* Initiate a PING */
     sleep(0.030);         /* Wait 30 milliseconds for an echo */
     bit_clear(RugBat_addr,0b001); /* Clear the echo line */
 }
void pwm_servo (int usec)
Set servo pules length to usec.
Definition at line 152 of file sonar.c.
References _toc5.
Referenced by set_servo().
 {
     pokeword(_toc5,usec<<1);   /* Convert 1/2 uSec ticks to 1 uSec units */
 }
float range ()
Compute range in feet. range() returns a meaningful result only when called after ping(). If range() returns -1.0 then no valid echo was received.
Definition at line 84 of file sonar.c.
References _tflg1, _tic1, and _tic2.
Referenced by detect_distance_sonar(), main(), and thermometer().
 {
     if((peek(_tflg1) & 0b10) == 0)     /* If IC2 didn't see echo */
         return -1.0;    /* Let calling routine decide which flag */
     else          /*  indicates no echo */
         return
             ((float)((peekword(_tic2) - peekword(_tic1)) >> 1) * 0.000569);
 }
void scan (int low_pos, int high_pos)
Make the servo scan back and forth between low_pos and high_pos Delay tells the servo how long to wait between steps
Definition at line 169 of file sonar.c.
References scan_delay, servo_pos, set_servo(), and sleep().
Referenced by main(), and move_behind().
 {
     /* Standard step size */
     int step = 1;
     /* Start can fail otherwise*/
     servo_pos = (low_pos + high_pos) / 2;
     while(1)
     {
         if((servo_pos < low_pos) || (servo_pos > high_pos))
         {
             /* Don't reverse instantly */
             sleep(3.0 * scan_delay);
             step = (- step);
         }
         servo_pos = servo_pos + step;
         set_servo(servo_pos);
         sleep(scan_delay);
     }
 }
void scan_display_position (int low_pos, int high_pos, int nLoop)
Make the servo scan back and forth between low_pos and high_pos Delay tells the servo how long to wait between steps ADD : Print the actual position of the rugBat between -100 & 100 And make a predetermined number of loop
Parameters
nLoop - number of laps remaining (must be superior to 1)
Definition at line 199 of file sonar.c.
References scan_delay, servo_pos, set_servo(), and sleep().
Referenced by main().
 {
     int step = 1;
     if(nLoop < 1)
     {
         return;
     }
     /* Standard step size */
     /* Start can fail otherwise*/
     servo_pos = (low_pos + high_pos) / 2;
     while(1)
     {
         if((servo_pos < low_pos) || (servo_pos > high_pos))
         {
             /* Don't reverse instantly */
             sleep(3.0 * scan_delay);
             step = (- step);
         }
         servo_pos = servo_pos + step;
         set_servo(servo_pos);
         printf("Position %d\n", servo_pos);
         sleep(scan_delay);
         if(servo_pos == 100)    /* A laps has been realized */
         {
             nLoop--;
         }
         if(nLoop == 0)    /* All loop are realized */
         {
             return;
         }
     }
 }
void set_servo (int pos)
Set the servo to a position between -100 and +100. Zero points forward.
Definition at line 160 of file sonar.c.
References pwm_servo(), servo_center, and servo_gain.
Referenced by main(), scan(), and scan_display_position().
 {
     pwm_servo(pos * servo_gain + servo_center);
 }
void sonar_disable_servo ()
Terminate servo action
Definition at line 114 of file sonar.c.
References RugBat_addr.
Referenced by sonar_servo_off().
 {
     poke(RugBat_addr,0b100); /* Speaker on, Sonar PWM off */
 }
void sonar_enable_servo ()
Make it possible for the servo to run.
Definition at line 106 of file sonar.c.
References RugBat_addr.
Referenced by sonar_init_servo().
 {
     poke(RugBat_addr,0b010); /* Speaker off, Sonar PWM on */
 }
void sonar_init_servo ()
Setup PA3 to produce the PWM signal for the servo.
Definition at line 122 of file sonar.c.
References _oc1d, _oc1m, _tctl1, _toc1, _toc5, and sonar_enable_servo().
Referenced by main().
 {
     sonar_enable_servo();
     bit_set(_tctl1,0b11);          /* OC5 sets pin PA3 */
     bit_set(_oc1m,0b1000);         /* OC1 affects PA3 */
     bit_clear(_oc1d,0b1000);       /* The OC1 effect is to clear PA3 */
     pokeword(_toc1,0x0000);        /* OC1 fires on TCNT overflow */
     pokeword(_toc5,0xFFFF);        /* On for maximum time */
 }
void sonar_servo_off ()
Turn the servo off.
Definition at line 135 of file sonar.c.
References _oc1m, _tctl1, and sonar_disable_servo().
Referenced by main().
 {
     sonar_disable_servo();
     bit_clear(_tctl1,0b11);        /* OC5 won't bother PA3 */
     bit_clear(_oc1m,0b1000);       /* Neither will OC1 */
 }
Variable Documentation
int _oc1d = 0x100D
Addresses of MC68HC11 internal registers used by RugBat
Definition at line 34 of file sonar.c.
Referenced by sonar_init_servo().
int _oc1m = 0x100C
Addresses of MC68HC11 internal registers used by RugBat
Definition at line 29 of file sonar.c.
Referenced by sonar_init_servo(), and sonar_servo_off().
int _tctl1 = 0x1020
Addresses of MC68HC11 internal registers used by RugBat
Definition at line 14 of file sonar.c.
Referenced by sonar_init_servo(), and sonar_servo_off().
int _tctl2 = 0x1021
Addresses of MC68HC11 internal registers used by RugBat
Definition at line 19 of file sonar.c.
Referenced by init_sonar().
int _tflg1 = 0x1023
Addresses of MC68HC11 internal registers used by RugBat
Definition at line 24 of file sonar.c.
Referenced by ping(), and range().
int _tic1 = 0x1010
Addresses of MC68HC11 internal registers used by RugBat
Definition at line 49 of file sonar.c.
Referenced by range().
int _tic2 = 0x1012
Addresses of MC68HC11 internal registers used by RugBat
Definition at line 54 of file sonar.c.
Referenced by range().
int _toc1 = 0x1016
Addresses of MC68HC11 internal registers used by RugBat
Definition at line 39 of file sonar.c.
Referenced by sonar_init_servo().
int _toc5 = 0x101E
Addresses of MC68HC11 internal registers used by RugBat
Definition at line 44 of file sonar.c.
Referenced by pwm_servo(), and sonar_init_servo().
int RugBat_addr = 0x4000 + (RugBat_jumper * 0x1000)
RugBat adress acess
Definition at line 9 of file sonar.c.
Referenced by ping(), sonar_disable_servo(), and sonar_enable_servo().
int RugBat_jumper = 0
Edit to select alternate jumper [0 - 3]
Definition at line 4 of file sonar.c.
float scan_delay = 0.01
Wait between commanded positions
Definition at line 101 of file sonar.c.
Referenced by scan(), and scan_display_position().
int servo_center = 1475
Empirical data for a Futaba S5102 servo: Min = 500 uSec, Max = 2450
Definition at line 146 of file sonar.c.
Referenced by set_servo().
int servo_gain = 10
Definition at line 147 of file sonar.c.
Referenced by set_servo().
int servo_pos = 0
Global, current commanded servo pos
Definition at line 96 of file sonar.c.
Referenced by scan(), and scan_display_position().