Rug-warrior: /root/Desktop/rug-warrior/libs/shared/encoder.c File Reference
encoder.c File Reference
Functions
void encoder_aux ()
void reset_encoder_aux ()
void encoder_reset ()
void check_encoder ()
Function Documentation
void check_encoder ()
use this to chech if your your running process or runing forever process or move_behind process is not blocked by somethink (shaft does not change)
Definition at line 63 of file encoder.c.
References _motor_left_speed_, _motor_right_speed_, _move_behind_process_running_, _running_process_running_, and sleep().
 {
     int last_right;
     int last_left;
     while(1)
     {
         sleep(_check_enc_yield_time_);
         if(last_right == _right_enc_counts_ &&
            last_left == _left_enc_counts_ &&
            _right_enc_counts_ != 0)
         {
             _running_process_running_ = 0;
             _move_behind_process_running_ = 0;
             /* stop rotation */
             _motor_left_speed_ = 0;
             _motor_right_speed_ = 0;
         }
         last_right = _right_enc_counts_;
         last_left = _left_enc_counts_;
     }
 }
void encoder_aux ()
count the switching state of encoders value are stored into left_enc_counts and right_enc_counts use this function under parallel thread
Definition at line 7 of file encoder.c.
References left_shaft(), and right_shaft().
Referenced by main().
 {
     int l_old, r_old, l_new, r_new;
     while(1)
     {
         l_new = left_shaft();
         r_new = right_shaft();
         if(l_old & ~l_new)
             _left_enc_counts_++;
         if(r_old & ~r_new)
             _right_enc_counts_++;
         l_old = l_new;
         r_old = r_new;
     }
 }
void encoder_reset ()
check if encoder_aux() process are not in running state can be not thread-safe
Definition at line 49 of file encoder.c.
 {
     _left_enc_counts_ = 0;
     _right_enc_counts_ = 0;
 }
void reset_encoder_aux ()
reset encoders count
Definition at line 30 of file encoder.c.
References sleep().
Referenced by rotate(), running(), and running_forever().
 {
     while(_left_enc_counts_)
     {
         _left_enc_counts_ = 0;
         sleep(0.001);
     }
     while(_right_enc_counts_)
     {
         _right_enc_counts_ = 0;
         sleep(0.001);
     }
 }