Rug-warrior: /root/Desktop/rug-warrior/libs/test/sonar.c File Reference
sonar.c File Reference
Functions
void main ()
Function Documentation
void main ()
Turn the RugBat then Compute the distance between the rugbat and the object
Definition at line 4 of file sonar.c.
References feetToCm(), init_sonar(), ping(), range(), scan_display_position(), sleep(), sonar_init_servo(), and sonar_servo_off().
 {
     /* Turn the RugBat*/
     sonar_init_servo();
     scan_display_position(-100,100, 5); /* 5 loop*/
     printf("END OF LOOPS");
     sleep(5.0);
     printf("\n\n");
     sonar_servo_off();
     /* Calculate the distance continious between an object and the sonar */
     init_sonar();
     while(1)
     {
         ping();
         printf("%f\n", feetToCm(range()));
         sleep(2.0);
     }
 }